In [1]:
import requests

url = "https://huggingface.co/datasets/zhengyun21/PMC-Patients-MetaData/resolve/main/PMID2Mesh.json"
file_name = "/Users/ahmadrezaie/2_My_papers/Synthetic_Data_Gen/code/PMC_Patient/PMID2Mesh.json"

# Send a GET request to download the file
response = requests.get(url)
if response.status_code == 200:
    # Write the content to a file
    with open(file_name, "wb") as file:
        file.write(response.content)
    print(f"Downloaded {file_name} successfully!")
else:
    print(f"Failed to download file. Status code: {response.status_code}")

Downloaded /Users/ahmadrezaie/2_My_papers/Synthetic_Data_Gen/code/PMC_Patient/PMID2Mesh.json successfully!

In [50]:
import pandas as pd
import json


# Path to the downloaded JSON file
file_path = "/Users/ahmadrezaie/2_My_papers/Synthetic_Data_Gen/code/PMC_Patient/PMID2Mesh.json"


# Load the JSON data
with open(file_path, "r") as file:
    data = json.load(file)

# Flatten the JSON structure
flattened_data = [
    {"ID": key, "Value": value} for key, values in data.items() for value in values
]

# Convert to DataFrame
df = pd.DataFrame(flattened_data)

# Display the DataFrame
len(df)

# Save to CSV if needed
#df.to_csv("/Users/ahmadrezaie/2_My_papers/Synthetic_Data_Gen/code/PMC_Patient/flattened_PMID2Mesh.csv", index=False)

355662

## unique number of MEsh terms

In [6]:
import json
import pandas as pd
from collections import Counter

# Path to your JSON file
file_path = "/Users/ahmadrezaie/2_My_papers/Synthetic_Data_Gen/code/PMC_Patient/PMID2Mesh.json"

# Load the JSON data
with open(file_path, "r") as file:
    data = json.load(file)

# Flatten the JSON structure into a single list of strings
all_strings = [value for values in data.values() for value in values]

# Count the frequency of each string
string_counts = Counter(all_strings)

# Convert to a DataFrame for easier handling
freq_df = pd.DataFrame(string_counts.items(), columns=["String", "Frequency"])

# Sort by frequency in descending order
freq_df = freq_df.sort_values(by="Frequency", ascending=False)

# Display the results
print("Total unique strings:", len(freq_df))
print(freq_df.head())

# Save to CSV if needed
freq_df.to_csv("""/Users/ahmadrezaie/2_My_papers/Synthetic_Data_Gen/code/PMC_Patient/
string_frequency_distribution.csv""", index=False)

Total unique strings: 13471
         String  Frequency
3        Humans      32277
5          Male      17995
52       Female      16485
49  Middle Aged      10663
0         Adult       9791

In [7]:
freq_df.head()

         String  Frequency
3        Humans      32277
5          Male      17995
52       Female      16485
49  Middle Aged      10663
0         Adult       9791

In [8]:
len(freq_df)

13471

## Mesh

In [10]:
import requests

# URL of the MeSH file
url = "https://nlmpubs.nlm.nih.gov/projects/mesh/2023/xmlmesh/desc2023.xml"
file_name = "/Users/ahmadrezaie/2_My_papers/Synthetic_Data_Gen/code/PMC_Patient/Mesh_desc2023.xml"  # Name of the downloaded file

# Send a GET request to download the file
response = requests.get(url, stream=True)

# Check if the request was successful
if response.status_code == 200:
    with open(file_name, "wb") as file:
        for chunk in response.iter_content(chunk_size=8192):  # Download in chunks
            file.write(chunk)
    print(f"File downloaded successfully: {file_name}")
else:
    print(f"Failed to download file. Status code: {response.status_code}")

File downloaded successfully: /Users/ahmadrezaie/2_My_papers/Synthetic_Data_Gen/code/PMC_Patient/Mesh_desc2023.xml

In [11]:
import xml.etree.ElementTree as ET
from tqdm import tqdm
import pandas as pd

# Path to the downloaded XML file
file_path = "/Users/ahmadrezaie/2_My_papers/Synthetic_Data_Gen/code/PMC_Patient/Mesh_desc2023.xml" 

# Parse the XML file
tree = ET.parse(file_path)
root = tree.getroot()

# Extract relevant data: DescriptorName and TreeNumber
data = []
descriptors = root.findall("DescriptorRecord")

# Wrap the iteration in tqdm for progress tracking
for descriptor in tqdm(descriptors, desc="Processing Descriptors"):
    descriptor_name = descriptor.find(".//DescriptorName/String").text  # Extract the Descriptor name
    tree_numbers = [tn.text for tn in descriptor.findall(".//TreeNumber")]  # Extract all TreeNumbers

    # Append as separate rows for each TreeNumber
    for tree_number in tree_numbers:
        data.append({"DescriptorName": descriptor_name, "TreeNumber": tree_number})

# Convert to a pandas DataFrame
df = pd.DataFrame(data)

# Display the first few rows
print(df.head())

# Save to a CSV if needed
output_path = "/Users/ahmadrezaie/2_My_papers/Synthetic_Data_Gen/code/PMC_Patient/mesh_descriptors.csv"
df.to_csv(output_path, index=False)

Processing Descriptors: 100%|██████████| 30454/30454 [00:00<00:00, 33558.65it/s]

  DescriptorName               TreeNumber
0     Calcimycin      D03.633.100.221.173
1        Temefos      D02.705.400.625.800
2        Temefos      D02.705.539.345.800
3        Temefos      D02.886.300.692.800
4      Abattoirs  J01.576.423.200.700.100

In [12]:
len(df)

63056

## Extracting only disease terms from PMC Patient

In [18]:
pmc= pd.read_csv("""/Users/ahmadrezaie/2_My_papers/Synthetic_Data_Gen/code/PMC_Patient/
string_frequency_distribution.csv""")

mesh= pd.read_csv("/Users/ahmadrezaie/2_My_papers/Synthetic_Data_Gen/code/PMC_Patient/mesh_descriptors.csv")

In [19]:
pmc.head()

        String  Frequency
0       Humans      32277
1         Male      17995
2       Female      16485
3  Middle Aged      10663
4        Adult       9791

In [20]:
mesh.head()

  DescriptorName               TreeNumber
0     Calcimycin      D03.633.100.221.173
1        Temefos      D02.705.400.625.800
2        Temefos      D02.705.539.345.800
3        Temefos      D02.886.300.692.800
4      Abattoirs  J01.576.423.200.700.100

In [36]:
# extracting strings for class C from Mesh:

disease_mesh = mesh[mesh["TreeNumber"].str.startswith("C")]
disease_mesh.head()

          DescriptorName                   TreeNumber
8         Abdomen, Acute      C23.888.592.612.054.200
9         Abdomen, Acute          C23.888.821.030.249
10    Abdominal Injuries                      C26.017
11   Abdominal Neoplasms                  C04.588.033
16  Abetalipoproteinemia  C16.320.565.398.500.440.500

In [37]:
len(disease_mesh)

12950

In [39]:
# there seem to be duplicates in names, but with different TreeNumber. I checked Mesh website and it seems, for example, Abdomen, Acute can be reached from different paths. 
# Website: https://www.ncbi.nlm.nih.gov/mesh/?term=Abdomen%2C+Acute
# I am using set to get the unique ones

mesh_disease_list= list(set(disease_mesh["DescriptorName"]))
mesh_disease_list

['Kallmann Syndrome',
 'Pasteurellaceae Infections',
 'Root Resorption',
 'Bruxism',
 'Coma, Post-Head Injury',
 'Sweating, Gustatory',
 'Postcholecystectomy Syndrome',
 'Craniofacial Fibrous Dysplasia',
 'Paresthesia',
 'Dentigerous Cyst',
 'Voice Disorders',
 'Multiple Acyl Coenzyme A Dehydrogenase Deficiency',
 'Chronic Urticaria',
 'Epidermolysis Bullosa Dystrophica',
 'Diabetes Mellitus, Type 1',
 'Costello Syndrome',
 'Tooth, Supernumerary',
 'Hypertrophy, Right Ventricular',
 'Muscle Rigidity',
 'Shaken Baby Syndrome',
 'Glucagonoma',
 'Helminthiasis, Animal',
 'Alcoholism',
 'Panuveitis',
 'Thyroglossal Cyst',
 'Swine Erysipelas',
 'Neoplasms, Neuroepithelial',
 'Signs and Symptoms',
 'Dental Fistula',
 'Renal Tubular Transport, Inborn Errors',
 'Aniseikonia',
 'Thanatophoric Dysplasia',
 'Pneumatosis Cystoides Intestinalis',
 'Tuberculosis, Bovine',
 'Diastema',
 'Chancre',
 'Cat-Scratch Disease',
 'Chondromatosis, Synovial',
 'Pemphigoid, Benign Mucous Membrane',
 'Hereditary Central Nervous System Demyelinating Diseases',
 'Fracture Dislocation',
 'Epilepsy',
 'Encephalitis, California',
 'Skull Fracture, Basilar',
 'Hypolipoproteinemias',
 'Warburg Effect, Oncologic',
 'Opsoclonus-Myoclonus Syndrome',
 'Factor XI Deficiency',
 'Hemophilia B',
 'Artificial Lens Implant Migration',
 'Limbal Stem Cell Deficiency',
 'Acinetobacter Infections',
 'Intestinal Perforation',
 'Diaschisis',
 'Parametritis',
 'Subcutaneous Emphysema',
 'Abdominal Abscess',
 'Blindness, Cortical',
 'Gingivitis, Necrotizing Ulcerative',
 'Pigmentation Disorders',
 'Respiratory Aspiration of Gastric Contents',
 'Stargardt Disease',
 'Leukocyte-Adhesion Deficiency Syndrome',
 'Corneal Edema',
 'Hyaline Membrane Disease',
 'Teratogenesis',
 'Crystalluria',
 'Oral Ulcer',
 'Pulmonary Atelectasis',
 'Thecoma',
 'Carcinosarcoma',
 'Eccrine Porocarcinoma',
 'Coxa Magna',
 'Dermatitis, Photoallergic',
 'Raynaud Disease',
 'Fucosidosis',
 'Porcine Reproductive and Respiratory Syndrome',
 'Dermatitis, Allergic Contact',
 'Familial Exudative Vitreoretinopathies',
 'Heart Arrest',
 'Tooth Migration',
 'Typhoid Fever',
 'Postphlebitic Syndrome',
 'Paraganglioma',
 'Myasthenic Syndromes, Congenital',
 'Carcinoma, Renal Cell',
 'ACTH Syndrome, Ectopic',
 'Hypersensitivity, Immediate',
 'Ovarian Torsion',
 'Hypertelorism',
 'Head Injuries, Penetrating',
 'Endometritis',
 'Glycogen Storage Disease Type VI',
 'Phencyclidine Abuse',
 'Drug Hypersensitivity',
 'Aortitis',
 'Polycystic Kidney, Autosomal Recessive',
 'Arrhythmia, Sinus',
 'Porphyrias',
 'Vulvodynia',
 'Primary Progressive Nonfluent Aphasia',
 'Echinostomiasis',
 'Laryngocele',
 'Astigmatism',
 'Tinnitus',
 'Lassa Fever',
 'Aneurysm, Ruptured',
 'Arthritis, Infectious',
 'Cryptogenic Organizing Pneumonia',
 'Toxoplasmosis',
 'Skin Ulcer',
 'Moyamoya Disease',
 'Typhlitis',
 'Chondrosarcoma',
 'Heterotaxy Syndrome',
 'Mixed Tumor, Malignant',
 'Retinal Degeneration',
 'Cranial Nerve Diseases',
 'Glomerulonephritis, IGA',
 'Genital Diseases',
 'Amino Acid Transport Disorders, Inborn',
 'Colitis, Collagenous',
 'Pectus Carinatum',
 'Odontodysplasia',
 'Hemoptysis',
 'Cystadenoma, Serous',
 'Tricuspid Valve Stenosis',
 'Infarction',
 'Paraplegia',
 'Pneumonia, Mycoplasma',
 'Metabolic Diseases',
 'Pancreatitis, Chronic',
 'Enterocolitis, Pseudomembranous',
 'Lipid Metabolism Disorders',
 'Urinary Bladder, Underactive',
 'Inferior Wall Myocardial Infarction',
 'Lipid Metabolism, Inborn Errors',
 'Neurocytoma',
 'Toxic Optic Neuropathy',
 'Thymus Neoplasms',
 'Nasal Obstruction',
 'Nocturnal Paroxysmal Dystonia',
 'African Horse Sickness',
 'Hemangioendothelioma',
 'Diarrhea',
 'Adenoma',
 'Lymphocytosis',
 'Myelolipoma',
 'Non-Filarial Lymphedema',
 'Hepatitis A',
 'Central Serous Chorioretinopathy',
 'Hypertensive Encephalopathy',
 'Hypothalamic Diseases',
 'Ichthyosiform Erythroderma, Congenital',
 'Larva Migrans, Visceral',
 'Hernia, Abdominal',
 'Cholesteatoma, Middle Ear',
 'Pythiosis',
 'Equinus Deformity',
 'Pleural Effusion',
 'Hepatic Encephalopathy',
 'Leukemia, Neutrophilic, Chronic',
 'Malignant Carcinoid Syndrome',
 'Pregnancy, Angular',
 'Onchocerciasis, Ocular',
 'Autonomic Dysreflexia',
 'Adenocarcinoma, Clear Cell',
 'Tinea cruris',
 'Vulvar Vestibulitis',
 'Pure Autonomic Failure',
 'Ornithine Carbamoyltransferase Deficiency Disease',
 'Gangliosidoses',
 'Fetal Hypoxia',
 'Gilbert Disease',
 'Carcinoma, Papillary, Follicular',
 'Hypohidrosis',
 'Anthrax',
 'Lip Neoplasms',
 'Discrete Subaortic Stenosis',
 'Ciliopathies',
 'Platelet Storage Pool Deficiency',
 'Dystonia',
 'Laboratory Infection',
 'Haemonchiasis',
 'Choroid Diseases',
 'Fusobacterium Infections',
 'Olfactory Nerve Injuries',
 'Rhinophyma',
 'Crigler-Najjar Syndrome',
 'Hip Contracture',
 'Dendritic Cell Sarcoma, Interdigitating',
 'Paraganglioma, Extra-Adrenal',
 'Leiomyosarcoma',
 'Hemangioma, Cavernous',
 'Laryngitis',
 'Tooth Attrition',
 'Gastroesophageal Reflux',
 'Adrenocortical Hyperfunction',
 'Liver Abscess, Pyogenic',
 'Vulvovaginitis',
 'Eye Burns',
 'Penile Induration',
 'Hyperopia',
 'Infant Death',
 'Pulmonary Emphysema',
 'Intra-Abdominal Hypertension',
 'Subdural Effusion',
 'Endoleak',
 'Hydronephrosis',
 'Pelvic Girdle Pain',
 'Nevus, Halo',
 'Ectodermal Dysplasia 3, Anhidrotic',
 'Neurologic Manifestations',
 'Panniculitis, Peritoneal',
 'Corneal Injuries',
 'Choristoma',
 'Tarsal Tunnel Syndrome',
 'Geographic Atrophy',
 'Bronchomalacia',
 'Theileriasis',
 'Lymphoma, B-Cell, Marginal Zone',
 'Eye Infections, Parasitic',
 'Carotid Body Tumor',
 'Hemiplegia',
 'Keratoconjunctivitis, Infectious',
 'Chronic Limb-Threatening Ischemia',
 'Convalescence',
 'Coccidioidomycosis',
 'Macroglossia',
 'Lower Extremity Deformities, Congenital',
 'Eye Diseases, Hereditary',
 'Hymenolepiasis',
 'Hyperphosphatemia',
 'Meconium Aspiration Syndrome',
 'Cachexia',
 'Movement Disorders',
 'Acidosis, Lactic',
 'Glossitis',
 'Exocrine Pancreatic Insufficiency',
 'Congenital, Hereditary, and Neonatal Diseases and Abnormalities',
 'Silicosis',
 'Gonadal Dysgenesis',
 'Oral Fistula',
 'Peripheral Nervous System Diseases',
 'Ecthyma',
 'Gardner Syndrome',
 'Infertility, Female',
 'Erythroplasia',
 'Uveitis, Posterior',
 'Multiple Trauma',
 'Neoplasms, Hormone-Dependent',
 'Uveal Diseases',
 'Autoimmune Hypophysitis',
 'Asthma-Chronic Obstructive Pulmonary Disease Overlap Syndrome',
 'Blindness',
 'Fetal Death',
 'Venous Insufficiency',
 'SUNCT Syndrome',
 'Basal Ganglia Diseases',
 'Fecal Impaction',
 'Soft Tissue Injuries',
 'Alkalosis',
 'Spinal Dysraphism',
 'Rhinorrhea',
 'Parapsoriasis',
 'Myelodysplastic Syndromes',
 'Oral Submucous Fibrosis',
 'Osteitis',
 'Histoplasmosis',
 'Rectocele',
 'Thyroid Carcinoma, Anaplastic',
 'Otorhinolaryngologic Diseases',
 'Panniculitis',
 'Heart Valve Diseases',
 'Metatarsal Valgus',
 'Bone Diseases, Metabolic',
 'Adenomyoepithelioma',
 'Urethral Neoplasms',
 'Pathological Conditions, Anatomical',
 'Calcinosis',
 'Nose Diseases',
 'Prenatal Injuries',
 'Vascular Remodeling',
 'Gyrate Atrophy',
 'Buruli Ulcer',
 'Auditory Perceptual Disorders',
 'Endophthalmitis',
 'Chronic Disease',
 'Carcinoma, Pancreatic Ductal',
 'Non-alcoholic Fatty Liver Disease',
 'Cytokine Release Syndrome',
 'Bone Diseases, Endocrine',
 'Extravasation of Diagnostic and Therapeutic Materials',
 'Strongylida Infections',
 'Ear Neoplasms',
 'Parathyroid Diseases',
 'Kearns-Sayre Syndrome',
 'Plasmablastic Lymphoma',
 'Mucormycosis',
 'Mycoplasma Infections',
 'Granuloma Annulare',
 'Narcotic-Related Disorders',
 'Arthrogryposis',
 'Posterior Cervical Sympathetic Syndrome',
 'Enteritis, Transmissible, of Turkeys',
 'Cystadenocarcinoma, Serous',
 'Wet Macular Degeneration',
 'Persistent Infection',
 'Septate Uterus',
 'Milk Sickness',
 'Hand-Arm Vibration Syndrome',
 'Uterine Rupture',
 'Carcinoma, Ehrlich Tumor',
 'Myopericytoma',
 'Scleroderma, Localized',
 'Common Variable Immunodeficiency',
 'Myasthenia Gravis',
 'Pulmonary Embolism',
 'Peritoneal Diseases',
 'Exercise-Induced Allergies',
 'Pyoderma Gangrenosum',
 'Hartnup Disease',
 'Nose Deformities, Acquired',
 'Hallux Limitus',
 'Epilepsy, Complex Partial',
 'Paralysis, Obstetric',
 'Muscle Hypotonia',
 'Erythema Chronicum Migrans',
 'Acne Keloid',
 'Persistent Fetal Circulation Syndrome',
 'Neuromuscular Diseases',
 'Adiposis Dolorosa',
 'Urologic Neoplasms',
 'Dirofilariasis',
 'Anomalous Left Coronary Artery',
 'Anemia, Megaloblastic',
 'Premenstrual Syndrome',
 'Mononeuropathies',
 'Folic Acid Deficiency',
 'Pregnancy Complications',
 'Stomach Ulcer',
 'Drug Resistant Epilepsy',
 'Empty Sella Syndrome',
 'Hemorrhagic Septicemia',
 'Hypoprothrombinemias',
 'Germinoma',
 'Leukoplakia, Hairy',
 'Mandibular Diseases',
 'Porphyria, Acute Intermittent',
 'Tuberculosis, Ocular',
 'Ulna Fractures',
 'Polyomavirus Infections',
 'Hearing Loss, Sensorineural',
 'Bacterial Infections and Mycoses',
 'Anisakiasis',
 'Leishmaniasis, Cutaneous',
 'Epilepsy, Benign Neonatal',
 'Retinal Necrosis Syndrome, Acute',
 'Micronuclei, Chromosome-Defective',
 'Cholecystitis',
 'Malignant Hyperthermia',
 'Polyradiculoneuropathy',
 'Posterior Leukoencephalopathy Syndrome',
 'Morgellons Disease',
 'Enterobiasis',
 'von Willebrand Disease, Type 2',
 'Vitamin A Deficiency',
 'Tenosynovitis',
 'Panniculitis, Nodular Nonsuppurative',
 'Disorders of Excessive Somnolence',
 'Mastocytoma',
 'Olecranon Fracture',
 'Adrenal Rest Tumor',
 'Angiokeratoma',
 'Lymphadenitis',
 'Caplan Syndrome',
 'Frontotemporal Dementia',
 'Myalgia',
 'Torovirus Infections',
 'Hypophosphatemia',
 'Sarcoma, Yoshida',
 'Heart Injuries',
 'Sweet Syndrome',
 'Gaucher Disease',
 'Darier Disease',
 'Encephalomyelitis, Western Equine',
 'Obesity, Metabolically Benign',
 'Granulomatosis with Polyangiitis',
 'Hemoglobin C Disease',
 'Scurvy',
 'Steatitis',
 'Tracheal Neoplasms',
 'Acute Aortic Syndrome',
 'Small Fiber Neuropathy',
 'Angiolymphoid Hyperplasia with Eosinophilia',
 'Marchiafava-Bignami Disease',
 'Smoke Inhalation Injury',
 'Arthritis',
 'Osteoblastoma',
 'Maple Syrup Urine Disease',
 'Thrombotic Stroke',
 'Gastrointestinal Neoplasms',
 'Hearing Loss, Noise-Induced',
 'Pneumonia, Pneumocystis',
 'Prion Diseases',
 'Leprosy, Paucibacillary',
 'Overbite',
 'Hypopituitarism',
 'Afibrinogenemia',
 'Uveitis',
 'Optic Atrophy, Autosomal Dominant',
 'Pyelonephritis',
 'Myelitis, Transverse',
 'Parasitic Diseases',
 'Insect Bites and Stings',
 'Leprosy, Borderline',
 'Duodenal Ulcer',
 'Rhinitis, Allergic, Seasonal',
 'Pediatric Obesity',
 'Occupational Diseases',
 'Jaundice, Obstructive',
 'Urinary Incontinence, Stress',
 'Lymphoma, Large-Cell, Immunoblastic',
 'Hemosiderosis',
 'Transposition of Great Vessels',
 'Sialadenitis',
 'Cadaver',
 'Agranulocytosis',
 'Meningeal Neoplasms',
 'Candidiasis, Cutaneous',
 'Neoplasms, Squamous Cell',
 'Erythrasma',
 'Vaccinia',
 'Neuritis',
 'Collagenous Sprue',
 'Neoplasms, Plasma Cell',
 'Microphthalmos',
 'Salmonella Infections',
 'Exanthema',
 'Tyrosinemias',
 'Choroid Plexus Neoplasms',
 'Aortic Diseases',
 'Skull Fracture, Depressed',
 'Alice in Wonderland Syndrome',
 'Hereditary Sensory and Autonomic Neuropathies',
 'Angiomyoma',
 'Long Term Adverse Effects',
 'Dysgammaglobulinemia',
 'Skin Diseases, Vesiculobullous',
 'Plasmacytoma',
 'Kartagener Syndrome',
 'Myoclonic Epilepsy, Juvenile',
 'Dog Diseases',
 'Hereditary Autoinflammatory Diseases',
 'Corneal Wavefront Aberration',
 'Tachycardia, Supraventricular',
 'Diphtheria',
 'Brain Damage, Chronic',
 'Toxascariasis',
 'Failure to Thrive',
 'Infections',
 'Aleutian Mink Disease',
 'Carney Complex',
 'Niemann-Pick Disease, Type A',
 'Poisoning',
 'Embryo Loss',
 'Wolfram Syndrome',
 'Clinical Deterioration',
 'Malaria, Falciparum',
 'Leukokeratosis, Hereditary Mucosal',
 'Pruritus Ani',
 'Peanut Hypersensitivity',
 'Langerhans Cell Sarcoma',
 'Hypercapnia',
 'Conjunctivitis, Acute Hemorrhagic',
 'Carcinoma, Basosquamous',
 'Precursor B-Cell Lymphoblastic Leukemia-Lymphoma',
 'Leprosy, Tuberculoid',
 'Hyperglycemia',
 'Onycholysis',
 'Hepatitis, Animal',
 'Yellow Nail Syndrome',
 'Myositis, Inclusion Body',
 'Embolic Stroke',
 'Psychophysiologic Disorders',
 'Hematoma, Subdural, Chronic',
 'Respiration Disorders',
 'Urogenital Diseases',
 'Placenta Accreta',
 'Pulmonary Adenomatosis, Ovine',
 'Lymphoma, Large-Cell, Anaplastic',
 'Esophagitis, Peptic',
 'Smallpox',
 'Descending Thoracic Aortic Aneurysm',
 'Pancreas Divisum',
 'Hepatomegaly',
 'Wolf-Hirschhorn Syndrome',
 'Retinal Dysplasia',
 'COVID-19',
 'Infant, Premature, Diseases',
 'Optic Nerve Diseases',
 'Tibial Plateau Fractures',
 'Graft Occlusion, Vascular',
 'Granulomatous Disease, Chronic',
 'Trismus',
 'Epilepsy, Frontal Lobe',
 'Intracranial Hemorrhages',
 'Diabetes Mellitus, Experimental',
 'Nephrosis, Lipoid',
 'Flea Infestations',
 'Caroli Disease',
 'Uterine Perforation',
 'Cogan Syndrome',
 'Salmonella Infections, Animal',
 'Heart Neoplasms',
 'Stomatitis, Denture',
 'Pneumovirus Infections',
 'Tetrasomy',
 'Cryptorchidism',
 'Leukoencephalopathies',
 'Bronchopulmonary Dysplasia',
 'Polyneuropathies',
 'Orthomyxoviridae Infections',
 'Actinomycosis, Cervicofacial',
 'Synesthesia',
 'Polycythemia Vera',
 'Acidosis',
 'Hyperkeratosis, Epidermolytic',
 'Placenta Diseases',
 "Monteggia's Fracture",
 'Leishmaniasis, Diffuse Cutaneous',
 'West Nile Fever',
 'Endolymphatic Hydrops',
 'Mastocytoma, Skin',
 'Pestivirus Infections',
 'Striae Distensae',
 'Carcinoma, Lobular',
 'Dry Eye Syndromes',
 'Radiation Injuries, Experimental',
 'Colorado Tick Fever',
 'Hypothyroidism',
 'Histiocytic Necrotizing Lymphadenitis',
 'Dysgeusia',
 'Hiccup',
 'Paraneoplastic Polyneuropathy',
 'Nasopharyngeal Diseases',
 'Fibromatosis, Aggressive',
 'Hematoma, Subdural',
 'Leukoencephalopathy, Progressive Multifocal',
 'Pharyngitis',
 'Thyroiditis, Autoimmune',
 'Cerebellar Ataxia',
 'Cholesteatoma',
 'Bone Diseases',
 'Pulmonary Alveolar Proteinosis',
 'Chest Pain',
 'Stuttering',
 'Amyotrophic Lateral Sclerosis',
 'Single Umbilical Artery',
 'Adenosarcoma',
 'Arenaviridae Infections',
 'Hematocolpos',
 'Mandibulofacial Dysostosis',
 'Muscle Cramp',
 'Niemann-Pick Disease, Type C',
 'Sleep Apnea, Obstructive',
 'Eczema',
 'Hypertension',
 'Intracranial Hemorrhage, Hypertensive',
 'Mixed Tumor, Mullerian',
 'Plummer-Vinson Syndrome',
 'Colonic Diseases',
 'Respiratory System Abnormalities',
 'Cell Transformation, Viral',
 'Cytomegalovirus Infections',
 'Spondylarthropathies',
 'Liver Cirrhosis, Experimental',
 'Chronic Exertional Compartment Syndrome',
 'Bulimia',
 'Bundle-Branch Block',
 'Kidney Neoplasms',
 'Epidermolysis Bullosa',
 'Jaw Fractures',
 'Isochromosomes',
 'Deafness',
 'Pulmonary Valve Insufficiency',
 'Glioblastoma',
 'Discitis',
 'Pregnancy, Interstitial',
 'Fibroma',
 'Dystonia Musculorum Deformans',
 'Herpangina',
 'Conjunctival Diseases',
 'Erysipelas',
 'Dysentery, Bacillary',
 'Polypoidal Choroidal Vasculopathy',
 'Multicystic Dysplastic Kidney',
 'LEOPARD Syndrome',
 'Paragonimiasis',
 'Encephalitis, Tick-Borne',
 'Superior Vena Cava Syndrome',
 'Thrombophlebitis',
 'POEMS Syndrome',
 'Thymus Hyperplasia',
 'Coronary Thrombosis',
 'Paraneoplastic Endocrine Syndromes',
 'Disease Models, Animal',
 'Prosopagnosia',
 'Avulavirus Infections',
 'Low Tension Glaucoma',
 'Fatty Liver, Alcoholic',
 'Polycythemia',
 'Rickets',
 'Temporomandibular Joint Disorders',
 'Jaw Cysts',
 'Hemianopsia',
 'Pneumocystis Infections',
 'Cardiomyopathies',
 'Leukemic Infiltration',
 'Hand Deformities',
 'Monosomy',
 'Environmental Illness',
 'Auditory Diseases, Central',
 'Facial Dermatoses',
 'Linitis Plastica',
 'Myotonic Dystrophy',
 'Cerebral Amyloid Angiopathy',
 'Spinal Osteophytosis',
 'Lymphoma, T-Cell, Peripheral',
 'Cardiomyopathy, Restrictive',
 'Silicotuberculosis',
 'Pityriasis Lichenoides',
 'Syphilis, Cutaneous',
 'Sepsis-Associated Encephalopathy',
 'Chronic Inducible Urticaria',
 'Median Arcuate Ligament Syndrome',
 'Wernicke Encephalopathy',
 'Cerebral Cortical Thinning',
 'Adamantinoma',
 'Persian Gulf Syndrome',
 'Nelson Syndrome',
 'Hypoadrenocorticism, Familial',
 'Urogenital Neoplasms',
 'Central Nervous System Viral Diseases',
 'Hypophysitis',
 'Botulism',
 'Meibomian Gland Dysfunction',
 'Mammary Analogue Secretory Carcinoma',
 'Intracranial Aneurysm',
 'Tubular Sweat Gland Adenomas',
 'Neoplasm Invasiveness',
 'Calcinosis Cutis',
 'Hyperostosis, Sternocostoclavicular',
 'Papilloma, Intraductal',
 'Immersion Foot',
 'Ependymoma',
 'Syringomyelia',
 'Fructose Metabolism, Inborn Errors',
 'Reproductive Tract Infections',
 'Travel-Related Illness',
 'Beriberi',
 'Gram-Positive Bacterial Infections',
 'Rigor Mortis',
 'Diffuse Axonal Injury',
 'Tick Toxicoses',
 'Ascaridiasis',
 'Peutz-Jeghers Syndrome',
 'Shoulder Pain',
 'Jaw Neoplasms',
 'Cystadenoma, Papillary',
 'Favism',
 'Body Weight',
 'Phagocyte Bactericidal Dysfunction',
 'Tay-Sachs Disease',
 'Tooth, Unerupted',
 'Migraine without Aura',
 'Hemangioblastoma',
 'Eczema, Dyshidrotic',
 'Mansonelliasis',
 'Cardiomyopathy, Alcoholic',
 'Glomerulonephritis, Membranoproliferative',
 'Oculomotor Nerve Diseases',
 'Glioma, Subependymal',
 'Dystonic Disorders',
 'Latent Infection',
 'Cardiomegaly',
 'Neoplasms, Bone Tissue',
 'Mononegavirales Infections',
 'Cancer Pain',
 'Photosensitivity Disorders',
 'Snoring',
 'Multiple Chronic Conditions',
 'Rheumatic Nodule',
 'Anemia, Pernicious',
 'Candidiasis',
 'Spinal Curvatures',
 'Forearm Injuries',
 'Tungiasis',
 'Catatonia',
 'Gestational Weight Gain',
 'Prader-Willi Syndrome',
 'Rubivirus Infections',
 'Periapical Periodontitis',
 'Athetosis',
 'African Swine Fever',
 'Parkinson Disease',
 'Diabetic Neuropathies',
 'Mushroom Poisoning',
 'Sertoli Cell Tumor',
 'Vasculitis',
 'Peptic Ulcer Hemorrhage',
 'Short Rib-Polydactyly Syndrome',
 'Allergic Fungal Sinusitis',
 'Esophageal Atresia',
 'Azoospermia',
 'Cerebral Arterial Diseases',
 'Takayasu Arteritis',
 'Fallopian Tube Diseases',
 'Oral Manifestations',
 'Granuloma, Pyogenic',
 'Enterocolitis',
 'Blood Protein Disorders',
 'AIDS-Related Opportunistic Infections',
 'Pharyngeal Diseases',
 'Rheumatic Diseases',
 'Deaf-Blind Disorders',
 'Crush Syndrome',
 'Dental Caries',
 'Pityriasis',
 'Osteitis Fibrosa Cystica',
 'Malabsorption Syndromes',
 'Dysuria',
 'Developmental Defects of Enamel',
 'Calciphylaxis',
 'Proteinuria',
 'Glaucoma',
 'Asphyxia Neonatorum',
 'Cumulative Trauma Disorders',
 'Rocky Mountain Spotted Fever',
 'Abscess',
 'Klebsiella Infections',
 'Dyskeratosis Congenita',
 'Poliomyelitis, Bulbar',
 'AIDS-Related Complex',
 'Myelinolysis, Central Pontine',
 'Elephantiasis, Filarial',
 'Leukodystrophy, Metachromatic',
 'Laryngomalacia',
 'Wasting Syndrome',
 'Pneumonia, Staphylococcal',
 'Erythroblastosis, Fetal',
 'Pulmonary Subvalvular Stenosis',
 'Aphasia, Broca',
 'Staphylococcal Scalded Skin Syndrome',
 'Anterior Compartment Syndrome',
 'Hyperplasia',
 'Trypanosomiasis',
 'Shy-Drager Syndrome',
 'Tuberculosis, Meningeal',
 'Paraparesis, Spastic',
 'Beckwith-Wiedemann Syndrome',
 'Anisometropia',
 'Puberty, Precocious',
 'Lung, Hyperlucent',
 'Ileal Neoplasms',
 'Meningitis, Fungal',
 'Neoplasms, Connective and Soft Tissue',
 'Alveolar Bone Loss',
 'Euglenozoa Infections',
 'Ureterolithiasis',
 'Out-of-Hospital Cardiac Arrest',
 'Osteoradionecrosis',
 'Healthcare-Associated Pneumonia',
 'Intracranial Arteriosclerosis',
 'Nystagmus, Congenital',
 'Epilepsy, Reflex',
 'Diverticulosis, Colonic',
 'Leukemia, Myeloid, Acute',
 'Ventilator-Induced Lung Injury',
 'Amnesia, Transient Global',
 'Hemolytic-Uremic Syndrome',
 'Lentigo',
 'Encephalitis, St. Louis',
 'Perimeningeal Infections',
 'Tracheobronchomegaly',
 'Myosarcoma',
 'Hypercholesterolemia',
 'Anemia, Sickle Cell',
 'Paraneoplastic Cerebellar Degeneration',
 'Lambert-Eaton Myasthenic Syndrome',
 'Solitary Fibrous Tumor, Pleural',
 'Hand Deformities, Acquired',
 'Spinal Stenosis',
 'Shock, Traumatic',

In [40]:
len(mesh_disease_list)

5004

In [41]:
# exctraing disease terms from PMC Patient:

pmc_filtered= pmc[pmc["String"].isin(mesh_disease_list)]
len(pmc_filtered)

4028

In [42]:
pmc_filtered.head(20)

                         String  Frequency
17               Lung Neoplasms       1277
25  Postoperative Complications        888
27   Neoplasm Recurrence, Local        858
29                     COVID-19        751
32               Adenocarcinoma        728
35              Liver Neoplasms        689
44                   Recurrence        578
46               Skin Neoplasms        557
47                Acute Disease        532
50             Breast Neoplasms        511
54          Disease Progression        483
60     Carcinoma, Squamous Cell        430
61                     Syndrome        424
62            Stomach Neoplasms        421
63             Kidney Neoplasms        420
65         Pancreatic Neoplasms        396
68               Abdominal Pain        388
72              Brain Neoplasms        360
75               Bone Neoplasms        347
78                     Melanoma        337

In [43]:
pmc["Frequency"].sum()

355662

In [49]:
pmc_filtered["percentage_total"]= (pmc["Frequency"]/pmc["Frequency"].sum())*100
pmc_filtered

/var/folders/wy/vcwn319j4kj7h2gnjqhn60tm0000gn/T/ipykernel_11527/3641551692.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pmc_filtered["percentage_total"]= (pmc["Frequency"]/pmc["Frequency"].sum())*100

                            String  Frequency  percentage_total
17                  Lung Neoplasms       1277          0.359049
25     Postoperative Complications        888          0.249675
27      Neoplasm Recurrence, Local        858          0.241240
29                        COVID-19        751          0.211156
32                  Adenocarcinoma        728          0.204689
...                            ...        ...               ...
13443               Oligomenorrhea          1          0.000281
13448              Focal Infection          1          0.000281
13449  Smoldering Multiple Myeloma          1          0.000281
13455            Whiplash Injuries          1          0.000281
13469            Rift Valley Fever          1          0.000281

[4028 rows x 3 columns]

In [48]:
= pmc_filtered[pmc_filtered["Frequency"]<=10]

len(ones)

2275