In [2]:
import pandas as pd
import numpy as np
import openai

In [3]:
def initialize_openai_client(api_key_file):
    """
    Initialize the OpenAI client with an API key read from a file.

    Args:
    api_key_file (str): The path to the file containing the OpenAI API key.

    Returns:
    openai.Client: An instance of the OpenAI client.
    """
    try:
        with open(api_key_file, 'r') as file:
            api_key = file.read().strip()
        client = openai.Client(api_key=api_key)
        return client
    except Exception as e:
        print(f"An error occurred: {e}")
        return None

In [4]:
client = initialize_openai_client("/Users/ahmadrezaie/DalPhD/Research/note_taking_v2/data/input/OpenAIkey.txt")

In [9]:
model = "gpt-4-1106-preview"
temperature=0
max_tokens=4052
top_p=1
frequency_penalty=0
presence_penalty=0


system_prompt = "Assume you are a very experienced physician. You will be given medical notes and your job is to change its format. \nThe notes must be in this format:\n\n1. Subjective: This section includes the patient's own description of their symptoms and complaints.\n\n2. Objective: This section includes observations and data gathered by the physician, such as vital signs, physical examination findings, and test results.\n\n3. Assessment: This section includes the physician's evaluation of the patient's condition, including a diagnosis or differential diagnosis.\n\n4. Plan: This section includes the physician's recommendations for treatment, management, and follow-up.\n You cannot add or remove anything, you must just change the format according to the instruction provided earlier.  "

In [10]:
def change_to_SOAP(note):
        note_response = client.chat.completions.create(
        model=model,
        temperature = temperature,
        max_tokens = max_tokens,
        top_p = top_p,
        frequency_penalty = frequency_penalty,
        presence_penalty = presence_penalty,
        messages=[
            {
                "role": "system",
                "content": system_prompt
            },
            {
                "role": "user",
                "content": note
            }
        ]
        )
        return note_response.choices[0].message.content

In [14]:
df = pd.read_csv("/Users/ahmadrezaie/papers/Synthetic_Data_Gen/data/input/TaskC-TrainingSet.csv")
df

,dataset,encounter_id,dialogue,note
0,virtassist,D2N001,"[doctor] hi , martha . how are you ?\n[patient...",CHIEF COMPLAINT\n\nAnnual exam.\n\nHISTORY OF ...
1,virtassist,D2N002,"[doctor] hi , andrew , how are you ?\n[patient...",CHIEF COMPLAINT\n\nJoint pain.\n\nHISTORY OF P...
2,virtassist,D2N003,"[doctor] hi , john . how are you ?\n[patient] ...",CHIEF COMPLAINT\n\nBack pain.\n\nHISTORY OF PR...
3,virtassist,D2N004,"[doctor] hi , james , how are you ?\n[patient]...",CHIEF COMPLAINT\n\nBack pain.\n\nHISTORY OF PR...
4,virtassist,D2N005,"[doctor] hey , ms. hill . nice to see you .\n[...",CC:\n\nRight middle finger pain.\n\nHPI:\n\nMs...
...,...,...,...,...
62,aci,D2N063,[doctor] so gloria is a 46 -year-old female to...,CHIEF COMPLAINT\n\nDyspnea.\n\nMEDICAL HISTORY...
63,aci,D2N064,[doctor] hey matthew how're you doing\n[patien...,CHIEF COMPLAINT\n\nLeft ankle pain.\n\nHISTORY...
64,aci,D2N065,[doctor] hey anna good to see you today so i'm...,CHIEF COMPLAINT\n\nRight ankle pain.\n\nHISTOR...
65,aci,D2N066,[doctor] hey gabriel i'm doctor scott good to ...,CHIEF COMPLAINT\n\nBack pain evaluation.\n\nME...
66,aci,D2N067,[doctor] hi elizabeth so i see that you were e...,CHIEF COMPLAINT\n\nRight knee injury.\n\nHISTO...

In [15]:
print(df["note"][0])

CHIEF COMPLAINT

Annual exam.

HISTORY OF PRESENT ILLNESS

Martha Collins is a 50-year-old female with a past medical history significant for congestive heart failure, depression, and hypertension who presents for her annual exam. It has been a year since I last saw the patient.

The patient has been traveling a lot recently since things have gotten a bit better. She reports that she got her COVID-19 vaccine so she feels safer about traveling. She has been doing a lot of hiking.

She reports that she is staying active. She has continued watching her diet and she is doing well with that. The patient states that she is avoiding salty foods that she likes to eat. She has continued utilizing her medications. The patient denies any chest pain, shortness of breath, or swelling in her legs.

Regarding her depression, she reports that she has been going to therapy every week for the past year. This has been really helpful for her. She denies suicidal or homicidal ideation.

The patient reports that she is still forgetting to take her blood pressure medication. She has noticed that when work gets more stressful, her blood pressure goes up. She reports that work has been going okay, but it has been a lot of long hours lately.

She endorses some nasal congestion from some of the fall allergies. She denies any other symptoms of nausea, vomiting, abdominal pain.

REVIEW OF SYSTEMS

• Ears, Nose, Mouth and Throat: Endorses nasal congestion from allergies.
• Cardiovascular: Denies chest pain or dyspnea on exertion.
• Respiratory: Denies shortness of breath.
• Gastrointestinal: Denies abdominal pain, nausea, or vomiting.
• Psychiatric: Endorses depression. Denies suicidal or homicidal ideations.

PHYSICAL EXAMINATION

• Cardiovascular: Grade 3/6 systolic ejection murmur.
1+ pitting edema of the bilateral lower extremities.

VITALS REVIEWED

• Blood Pressure: Elevated.

RESULTS

Echocardiogram demonstrates decreased ejection fraction of 45%. Mitral regurgitation is present.

Lipid panel: Elevated cholesterol.

ASSESSMENT AND PLAN

Martha Collins is a 50-year-old female with a past medical history significant for congestive heart failure, depression, and hypertension who presents for her annual exam.

Congestive heart failure.
• Medical Reasoning: She has been compliant with her medication and dietary modifications. Her previous year's echocardiogram demonstrated a reduced ejection fraction of 45%, as well as some mitral regurgitation. Her cholesterol levels were slightly elevated on her lipid panel from last year.
• Additional Testing: We will order a repeat echocardiogram. We will also repeat a lipid panel this year.
• Medical Treatment: She will continue with her current medications. We will increase her lisinopril to 40 mg daily and initiate Lasix 20 mg daily.
• Patient Education and Counseling: I encouraged her to continue with dietary modifications.

Depression.
• Medical Reasoning: She is doing well with weekly therapy.

Hypertension.
• Medical Reasoning: She has been compliant with dietary modifications but has been inconsistent with the use of her medication. She attributes elevations in her blood pressure to increased stress.
• Medical Treatment: We will increase her lisinopril to 40 mg daily as noted above.
• Patient Education and Counseling: I encouraged the patient to take her lisinopril as directed. I advised her to monitor her blood pressures at home for the next week and report them to me.

Healthcare maintenance.
• Medical Reasoning: The patient is due for her routine mammogram.
• Additional Testing: We will order a mammogram and have this scheduled for her.

Patient Agreements: The patient understands and agrees with the recommended medical treatment plan.

In [13]:
soap = change_to_SOAP(df["note"][0])
print(soap)

1. Subjective:
Martha Collins, a 50-year-old female with a history of congestive heart failure, depression, and hypertension, presents for her annual exam. She reports staying active with hiking and maintaining a diet low in salt. She has been compliant with her medications and has received her COVID-19 vaccine. She denies experiencing chest pain, shortness of breath, or leg swelling. She attends weekly therapy sessions for depression and denies suicidal or homicidal ideation. However, she admits to occasionally forgetting to take her blood pressure medication, especially during stressful work periods. She also reports nasal congestion due to fall allergies but denies nausea, vomiting, or abdominal pain.

2. Objective:
- Ears, Nose, Mouth, and Throat: Nasal congestion from allergies.
- Cardiovascular: No chest pain or dyspnea on exertion; 3/6 systolic ejection murmur; 1+ pitting edema of the bilateral lower extremities.
- Respiratory: No shortness of breath.
- Gastrointestinal: No abdominal pain, nausea, or vomiting.
- Psychiatric: Depression present; no suicidal or homicidal ideations.
- Vitals: Elevated blood pressure.
- Test Results: Echocardiogram shows decreased ejection fraction of 45% and mitral regurgitation. Elevated cholesterol levels on lipid panel.

3. Assessment:
- Congestive Heart Failure: Compliant with medication and dietary modifications. Previous echocardiogram showed reduced ejection fraction and mitral regurgitation. Elevated cholesterol levels.
- Depression: Responding well to weekly therapy.
- Hypertension: Compliant with dietary modifications but inconsistent with medication adherence. Stress-related blood pressure elevations noted.
- Healthcare Maintenance: Due for routine mammogram.

4. Plan:
- Congestive Heart Failure: Order repeat echocardiogram and lipid panel. Continue current medications, increase lisinopril to 40 mg daily, and initiate Lasix 20 mg daily. Encourage ongoing dietary modifications.
- Depression: Continue with weekly therapy.
- Hypertension: Increase lisinopril to 40 mg daily. Encourage consistent medication adherence and home blood pressure monitoring for the next week, with instructions to report readings.
- Healthcare Maintenance: Order and schedule mammogram.
- Patient Education and Counseling: Reinforce the importance of medication adherence, dietary modifications, and stress management.
- Patient Agreements: Patient understands and agrees with the recommended medical treatment plan.

In [16]:
batch_size = 1
processed_count = 0

for index, row in df.iterrows():
    try:
        # Process each row's note to get SOAP content
        df.at[index, 'note_SOAP'] = change_to_SOAP(row['note'])
        processed_count += 1

    except Exception as e:
        # Log the error
        print(f"Error processing row {index}: {e}")
    
    finally:
        # Save the DataFrame every batch_size rows or if an exception occurs
        if processed_count % batch_size == 0 or index == len(df) - 1:
            df.to_csv('/Users/ahmadrezaie/papers/Synthetic_Data_Gen/data/input/TaskC-TrainingSet_SOAP.csv', index=False)
            print(f"Saved progress at row {index}")

# Additional final save, if not already saved
if processed_count % batch_size != 0:
    df.to_csv('/Users/ahmadrezaie/papers/Synthetic_Data_Gen/data/input/TaskC-TrainingSet_SOAP_final.csv', index=False)
    print("All data processed and saved.")

Saved progress at row 0
Saved progress at row 1
Saved progress at row 2
Saved progress at row 3
Saved progress at row 4
Saved progress at row 5
Saved progress at row 6
Saved progress at row 7
Saved progress at row 8
Saved progress at row 9
Saved progress at row 10
Saved progress at row 11
Saved progress at row 12
Saved progress at row 13
Saved progress at row 14
Saved progress at row 15
Saved progress at row 16
Saved progress at row 17
Saved progress at row 18
Saved progress at row 19
Saved progress at row 20
Saved progress at row 21
Saved progress at row 22
Saved progress at row 23
Saved progress at row 24
Saved progress at row 25
Saved progress at row 26
Saved progress at row 27
Saved progress at row 28
Saved progress at row 29
Saved progress at row 30
Saved progress at row 31
Saved progress at row 32
Saved progress at row 33
Saved progress at row 34
Saved progress at row 35
Saved progress at row 36
Saved progress at row 37
Saved progress at row 38
Saved progress at row 39
Saved progress at row 40
Saved progress at row 41
Saved progress at row 42
Saved progress at row 43
Saved progress at row 44
Saved progress at row 45
Saved progress at row 46
Saved progress at row 47
Saved progress at row 48
Saved progress at row 49
Saved progress at row 50
Saved progress at row 51
Saved progress at row 52
Saved progress at row 53
Saved progress at row 54
Saved progress at row 55
Saved progress at row 56
Saved progress at row 57
Saved progress at row 58
Saved progress at row 59
Saved progress at row 60
Saved progress at row 61
Saved progress at row 62
Saved progress at row 63
Saved progress at row 64
Saved progress at row 65
Saved progress at row 66

In [17]:
# test set:

df_test = pd.read_csv("/Users/ahmadrezaie/papers/Synthetic_Data_Gen/data/input/clinicalnlp_taskC_test2.csv")
df_test

,dataset,encounter_id,dialogue,note
0,virtassist,D2N128,"[doctor] hi , carolyn . how are you ?\n[patien...",CHIEF COMPLAINT\n\nFollow-up of chronic proble...
1,virtassist,D2N129,"[doctor] good afternoon , beverly . good to se...",CHIEF COMPLAINT\n\nAnnual exam.\n\nHISTORY OF ...
2,virtassist,D2N130,"[doctor] hi , anna , how are you ?\n[patient] ...",CHIEF COMPLAINT\n\nJoint pain.\n\nHISTORY OF P...
3,virtassist,D2N131,"hi , susan , how are you ?\n[patient] good . h...",CHIEF COMPLAINT\n\nHigh blood pressure check.\...
4,virtassist,D2N132,"[doctor] hello mrs. lee , i see you're here fo...",CC:\n\nBack pain.\n\nHPI:\n\nMs. Lee is a 40-y...
5,virtassist,D2N133,"[doctor] good morning rebecca , nice to see yo...",CHIEF COMPLAINT\n\nJoint pain\n\nHISTORY OF PR...
6,virtassist,D2N134,[doctor] we're gon na go right to the front- ....,CHIEF COMPLAINT\n\nAbnormal labs.\n\nHISTORY O...
7,virtassist,D2N135,"[patient] um , i have high blood sugar . yeah ...",CHIEF COMPLAINT\n\nEvaluation of high blood su...
8,virtassist,D2N136,"[doctor] hi janet , how are you ?\n[patient] g...",CHIEF COMPLAINT\n\nJoint pain.\n\nHISTORY OF P...
9,virtassist,D2N137,"[doctor] morning christine , nice to see you ....",CHIEF COMPLAINT\n\nAnnual exam.\n\nHISTORY OF ...
10,virtscribe,D2N138,[doctor] next patient is emily hernandez . dat...,"CHIEF COMPLAINT\n\nFollow-up for asthma, aller..."
11,virtscribe,D2N139,"[doctor] all right , new patient , jordan robe...",CHIEF COMPLAINT\n\nHigh blood pressure and pal...
12,virtscribe,D2N140,"[doctor] brittany edwards , 07 , 1898 . she is...",CHIEF COMPLAINT\n\nFollow up irritable bowel s...
13,virtscribe,D2N141,"[doctor] okay , so our next patient is christo...",CHIEF COMPLAINT\n\nFollow up adult hydrocephal...
14,virtscribe,D2N142,"[doctor] amanda taylor , birth date october 31...",CHIEF COMPLAINT\n\nHypertension.\nAlcohol use ...
15,virtscribe,D2N143,[doctor] next patient is grace ross . date of ...,CHIEF COMPLAINT\n\nFull-spectrum sexually tran...
16,virtscribe,D2N144,"[doctor] tyler nelson , date of birth : 3 , 6 ...",CHIEF COMPLAINT\n\nRheumatoid arthritis manage...
17,virtscribe,D2N145,"[doctor] uh , mrn49282721 . patient's name is ...",CHIEF COMPLAINT\n\nFollow-up for perioral derm...
18,aci,D2N146,[doctor] hey good morning bobby how are you\n[...,CHIEF COMPLAINT\n\nAbdominal pain.\n\nMEDICAL ...
19,aci,D2N147,[doctor] hi matthew how are you the medical as...,CHIEF COMPLAINT\n\nRight shoulder injury.\n\nH...
20,aci,D2N148,[doctor] hi jeremy how are you the medical ass...,HISTORY OF PRESENT ILLNESS\n\nJeremy Adams is ...
21,aci,D2N149,[doctor] so dennis is a 57 -year-old male toda...,CHIEF COMPLAINT\n\nShortness of breath with he...
22,aci,D2N150,[doctor] alright scott so so i understand that...,CHIEF COMPLAINT\n\nRight knee injury.\n\nHISTO...
23,aci,D2N151,[doctor] alright teresa i see here in your cha...,CHIEF COMPLAINT\n\nRight elbow pain.\n\nHISTOR...
24,aci,D2N152,[doctor] good morning noah tell me a little bi...,CHIEF COMPLAINT\n\nBack pain.\n\nMEDICAL HISTO...
25,aci,D2N153,[patient] i hope i did n't hurt it again\n[doc...,HISTORY OF PRESENT ILLNESS\n\nGregory Price is...
26,aci,D2N154,[doctor] hi dennis how are you today\n[patient...,HISTORY OF PRESENT ILLNESS\n\nDennis Martin is...
27,aci,D2N155,[doctor] so hey christina good to see you toda...,CHIEF COMPLAINT\n\nNon-healing right foot ulce...
28,aci,D2N156,[doctor] alright julia so you've been coming t...,CHIEF COMPLAINT\n\nFollow up status post infer...
29,aci,D2N157,[doctor] hey jose how are you doing it's been ...,CHIEF COMPLAINT\n\nFollow-up.\n\nMEDICAL HISTO...
30,aci,D2N158,[doctor] yeah so sorry so barbara is a 31 -yea...,CHIEF COMPLAINT\n\nAbdominal pain.\n\nMEDICAL ...
31,aci,D2N159,[doctor] good afternoon alexis i understand yo...,CHIEF COMPLAINT\n\nRight hand pain.\n\nHISTORY...
32,aci,D2N160,[doctor] hey good to see you philip so i see h...,CHIEF COMPLAINT\n\nRight elbow pain.\n\nREVIEW...
33,aci,D2N161,[doctor] patient is an 82 -year-old male with ...,CHIEF COMPLAINT\n\nHospital follow-up after ac...
34,aci,D2N162,[patient] okay\n[doctor] hi gregory hi how are...,CHIEF COMPLAINT\n\nRight ankle pain and swelli...
35,aci,D2N163,[doctor] julie cruz is a 17 -year-old non- bin...,CHIEF COMPLAINT\n\nHypercholesterolemia.\n\nSO...
36,aci,D2N164,[doctor] so elizabeth is a 53 -year-old female...,CHIEF COMPLAINT\n\nChest pain on exertion.\n\n...
37,aci,D2N165,[doctor] hey sophia how are you doing today\n[...,CHIEF COMPLAINT\n\nBilateral knee pain.\n\nHIS...
38,aci,D2N166,[doctor] hey kyle so i see here on your chart ...,HISTORY OF PRESENT ILLNESS\n\nKyle Morales is ...
39,aci,D2N167,[doctor] angela good to see you today so i'm w...,HISTORY OF PRESENT ILLNESS\n\nAngela Powell is...

In [20]:
batch_size = 1
processed_count = 0

for index, row in df_test.iterrows():
    try:
        # Process each row's note to get SOAP content
        df_test.at[index, 'note_SOAP'] = change_to_SOAP(row['note'])
        processed_count += 1

    except Exception as e:
        # Log the error
        print(f"Error processing row {index}: {e}")
    
    finally:
        # Save the DataFrame every batch_size rows or if an exception occurs
        if processed_count % batch_size == 0 or index == len(df) - 1:
            df_test.to_csv('/Users/ahmadrezaie/papers/Synthetic_Data_Gen/data/input/clinicalnlp_taskC_test2_SOAP.csv', index=False)
            print(f"Saved progress at row {index}")

# Additional final save, if not already saved
if processed_count % batch_size != 0:
    df_test.to_csv('/Users/ahmadrezaie/papers/Synthetic_Data_Gen/data/input/clinicalnlp_taskC_test2_SOAP_final.csv', index=False)
    print("All data processed and saved.")

Saved progress at row 0
Saved progress at row 1
Saved progress at row 2
Saved progress at row 3
Saved progress at row 4
Saved progress at row 5
Saved progress at row 6
Saved progress at row 7
Saved progress at row 8
Saved progress at row 9
Saved progress at row 10
Saved progress at row 11
Saved progress at row 12
Saved progress at row 13
Saved progress at row 14
Saved progress at row 15
Saved progress at row 16
Saved progress at row 17
Saved progress at row 18
Saved progress at row 19
Saved progress at row 20
Saved progress at row 21
Saved progress at row 22
Saved progress at row 23
Saved progress at row 24
Saved progress at row 25
Saved progress at row 26
Saved progress at row 27
Saved progress at row 28
Saved progress at row 29
Saved progress at row 30
Saved progress at row 31
Saved progress at row 32
Saved progress at row 33
Saved progress at row 34
Saved progress at row 35
Saved progress at row 36
Saved progress at row 37
Saved progress at row 38
Saved progress at row 39
Error processing row 40: Error code: 400 - {'error': {'message': "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Saved progress at row 40
Error processing row 41: Error code: 400 - {'error': {'message': "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Saved progress at row 41
Error processing row 42: Error code: 400 - {'error': {'message': "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Saved progress at row 42
Error processing row 43: Error code: 400 - {'error': {'message': "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Saved progress at row 43
Error processing row 44: Error code: 400 - {'error': {'message': "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Saved progress at row 44
Error processing row 45: Error code: 400 - {'error': {'message': "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Saved progress at row 45
Error processing row 46: Error code: 400 - {'error': {'message': "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Saved progress at row 46
Error processing row 47: Error code: 400 - {'error': {'message': "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Saved progress at row 47
Error processing row 48: Error code: 400 - {'error': {'message': "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Saved progress at row 48
Error processing row 49: Error code: 400 - {'error': {'message': "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Saved progress at row 49
Error processing row 50: Error code: 400 - {'error': {'message': "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Saved progress at row 50
Error processing row 51: Error code: 400 - {'error': {'message': "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Saved progress at row 51
Error processing row 52: Error code: 400 - {'error': {'message': "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Saved progress at row 52
Error processing row 53: Error code: 400 - {'error': {'message': "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Saved progress at row 53
Error processing row 54: Error code: 400 - {'error': {'message': "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Saved progress at row 54
Error processing row 55: Error code: 400 - {'error': {'message': "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Saved progress at row 55
Error processing row 56: Error code: 400 - {'error': {'message': "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Saved progress at row 56
Error processing row 57: Error code: 400 - {'error': {'message': "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Saved progress at row 57
Error processing row 58: Error code: 400 - {'error': {'message': "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Saved progress at row 58
Error processing row 59: Error code: 400 - {'error': {'message': "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Saved progress at row 59
Error processing row 60: Error code: 400 - {'error': {'message': "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Saved progress at row 60
Error processing row 61: Error code: 400 - {'error': {'message': "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Saved progress at row 61
Error processing row 62: Error code: 400 - {'error': {'message': "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Saved progress at row 62
Error processing row 63: Error code: 400 - {'error': {'message': "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Saved progress at row 63
Error processing row 64: Error code: 400 - {'error': {'message': "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Saved progress at row 64
Error processing row 65: Error code: 400 - {'error': {'message': "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Saved progress at row 65
Error processing row 66: Error code: 400 - {'error': {'message': "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Saved progress at row 66