In [1]:
import pandas as pd

In [2]:
df= pd.read_csv("/Users/ahmadrezaie/2_My_papers/Synthetic_Data_Gen/data/output/notes_dial_pairs/phase_2_to_12_combined/total_data.csv", sep="|")
df.head()

,Unnamed: 0,Disease Description,Scenario,Note,Polished Note,Abbreviated Note,Role,dial,polished_dial
0,0,PAIN IN LEFT KNEE,ROLE: Orthopedic Specialist\n\n1) Medical Outc...,**1. Subjective:**\n\n **Chief Complaint (CC...,**1. Subjective:**\n\n **Chief Complaint (CC...,**1. Subjective:**\n\n **CC:**\n - L knee ...,Orthopedic Specialist,**Doctor:** Hello! It’s good to see you today....,[doctor]: Hello! It’s good to see you today. H...
1,1,PAIN IN LEFT KNEE,ROLE: General Physician\n\n- **Medical Outcome...,**1. Subjective:**\n\n - **Chief Complaint (...,**1. Subjective:**\n\n - **Chief Complaint (...,**1. Subjective:**\n\n - **CC:** Pain in L k...,General Physician,**CHIEF COMPLAINT**\n\nPain in left knee.\n\n*...,"[doctor] Hi there, how are you today?\n\n[pati..."
2,2,PAIN IN LEFT KNEE,ROLE: Family Medicine Physician \n\n** 1) Medi...,#####\n**1. Subjective:**\n\n**Chief Complaint...,**1. Subjective:**\n\n**Chief Complaint (CC):*...,**1. Subjective:**\n\n**CC:**\nSevere R hip pa...,Family Medicine Physician,"[doctor] Good morning, how are you doing today...","[doctor] Good morning, how are you doing today..."
3,3,PAIN IN LEFT KNEE,ROLE: Orthopedic Specialist\n\n**Scenario:**\n...,**1. Subjective:**\n\n**Chief Complaint (CC):*...,**1. Subjective:**\n\n**Chief Complaint (CC):*...,**1. Subjective:**\n\n**CC:** \nModerate knee...,Orthopedic Specialist,[doctor] Good morning! How are you feeling tod...,[doctor] Good morning! How are you feeling tod...
4,4,PAIN IN LEFT KNEE,ROLE: Orthopedic Specialist\n\n** Medical Outc...,#####\n**1. Subjective:**\n\n**Chief Complaint...,#####\n**1. Subjective:**\n\n**Chief Complaint...,#####\n**1. Subjective:**\n\n**CC:** \nModera...,Orthopedic Specialist,"[doctor]: Hello Mr. Doe, how are you doing tod...","[doctor]: Hello Mr. Doe, how are you doing tod..."

In [3]:
print(df["Polished Note"][10])

### Medical Note

#### 1. Subjective:

**Chief Complaint (CC):**
Fatigue, dizziness, and occasional nausea for the past 3 weeks.

**History of Present Illness (HPI):**
Mr. Cortez is a 45-year-old Hispanic male with a medical history of prediabetes and hypertension. He presents with complaints of ongoing fatigue, dizziness, and occasional nausea for the past 3 weeks. These symptoms occur daily, with episodes of dizziness happening 2-3 times per day, significantly affecting his ability to perform daily tasks at work and home.

Mr. Cortez reports that his sleep is often disturbed, averaging 6 hours per night. His diet is high in processed foods, with low intake of fruits and vegetables. He does not exercise regularly and smokes 5 cigarettes per day. He consumes alcohol socially, approximately 4-5 drinks per week, and denies any recreational drug use. Due to his symptoms, he has minimal recreational activities.

He expresses frustration with the lack of improvement despite following his current treatment regimen and is cooperative but clearly distressed about his ongoing condition.

**Review of Systems (ROS):**
- **General:** Moderate fatigue, dizziness, occasional nausea.
- **Cardiovascular:** Denies chest pain, palpitations, or edema.
- **Respiratory:** Denies shortness of breath, cough, or wheezing.
- **Gastrointestinal:** Occasional nausea, denies vomiting, diarrhea, or constipation.
- **Neurological:** Dizziness, denies headaches, seizures, or focal neurological deficits.
- **Musculoskeletal:** No joint pain or swelling.
- **Psychiatric:** Feels frustrated and anxious due to symptoms.

#### 2. Objective:

**General Appearance:**
Appears tired, no acute distress.

**Vital Signs:**
- Blood Pressure: 140/88 mmHg
- Heart Rate: 78 bpm
- Respiratory Rate: 16 breaths per minute
- Temperature: 98.6 °F
- Oxygen Saturation: 98% on room air

**Physical Examination:**
- **Cardiovascular:** Regular rate and rhythm, no murmurs.
- **Respiratory:** Clear to auscultation bilaterally.
- **Neurological:** Alert and oriented, no focal deficits.
- **Abdomen:** Soft, non-tender, no hepatosplenomegaly.
- **Musculoskeletal:** Normal range of motion, no tenderness.

#### 3. Assessment:

Mr. Cortez is a 45-year-old male with prediabetes and hypertension, presenting with moderate fatigue, dizziness, and occasional nausea over the past three weeks. The differential diagnosis includes dehydration, electrolyte imbalance, or possible endocrine/metabolic disorder given his symptoms and medical history.

#### 4. Plan:

1. **Monitor Symptoms:** Encourage Mr. Cortez to keep a symptom diary and monitor for any changes.

2. **Hydration:** Advise Mr. Cortez to increase fluid intake and ensure adequate hydration.

3. **Laboratory Testing:** Await results of the biochemistry panel, including glucose, electrolytes, renal, and liver function tests.

4. **Endocrinology Referral:** Refer Mr. Cortez to Dr. Karen Liu, endocrinologist, for further evaluation of potential underlying endocrine or metabolic causes.

5. **Follow-Up:** Schedule a follow-up visit in 1 week to review lab results and reassess symptoms.

6. **Lifestyle and Diet Counseling:** Educate Mr. Cortez on the importance of a balanced diet, regular exercise, and smoking cessation. Provide resources for dietary changes and smoking cessation support.

Patient understands and agrees with the plan. He was reminded to follow up in one week or sooner if symptoms worsen.

---

**Signature:**
Dr. [Your Name], MD
General Physician
Private Practice

In [4]:
filtered_df= df[["Disease Description", "Polished Note", "polished_dial"]]
filtered_df.head()

,Disease Description,Polished Note,polished_dial
0,PAIN IN LEFT KNEE,**1. Subjective:**\n\n **Chief Complaint (CC...,[doctor]: Hello! It’s good to see you today. H...
1,PAIN IN LEFT KNEE,**1. Subjective:**\n\n - **Chief Complaint (...,"[doctor] Hi there, how are you today?\n\n[pati..."
2,PAIN IN LEFT KNEE,**1. Subjective:**\n\n**Chief Complaint (CC):*...,"[doctor] Good morning, how are you doing today..."
3,PAIN IN LEFT KNEE,**1. Subjective:**\n\n**Chief Complaint (CC):*...,[doctor] Good morning! How are you feeling tod...
4,PAIN IN LEFT KNEE,#####\n**1. Subjective:**\n\n**Chief Complaint...,"[doctor]: Hello Mr. Doe, how are you doing tod..."

In [4]:
filtered_df.to_csv("/Users/ahmadrezaie/2_My_papers/Synthetic_Data_Gen/data/output/notes_dial_pairs/phase_2_to_12_combined/total_data_filtered.csv",sep="|")

In [6]:
sample_df = filtered_df.sample(10)

sample_df

,Disease Description,Polished Note,polished_dial
7668,PORTAL VEIN THROMBOSIS,### Subjective:\n\n**Chief Complaint (CC):**\n...,"[doctor]: Hi, how are you doing today?\n\n[pat..."
9568,OTHER INTRAARTICULAR FRACTURE OF LOWER END OF ...,#####\n**1. Subjective:**\n\n**Chief Complaint...,"[doctor]: Hi there, how are you doing today?\n..."
2117,ISCHEMIC CARDIOMYOPATHY,### Medical Note\n\n**1. Subjective:**\n\n**Ch...,"[doctor] Hi, how are you doing today?\n\n[pati..."
3310,OTHER SPECIFIED ABNORMAL IMMUNOLOGICAL FINDING...,**1. Subjective:**\n\n**CHIEF COMPLAINT**\n\nO...,"[doctor]: Hi there, good to see you again. How..."
782,ENCOUNTER FOR PREPROCEDURAL LABORATORY EXAMINA...,### MEDICAL NOTE\n\n**1. Subjective:**\n\n**Ch...,"[doctor]: Hi there, how are you today?\n\n[pat..."
7399,"BIPOLAR DISORDER, CURRENT EPISODE DEPRESSED, S...",**1. Subjective:**\n\n**Chief Complaint (CC):*...,"[doctor]: Hi, I’m Dr. Smith. It's nice to meet..."
3105,"ABNORMAL FINDING OF BLOOD CHEMISTRY, UNSPECIFIED",**1. Subjective:**\n\nCHIEF COMPLAINT\n\nFollo...,"[doctor]: Hi John, how are you doing today?\n\..."
3548,GASTROPARESIS,**1. Subjective:**\n\n**Chief Complaint (CC):*...,"[doctor] Hi John, how are you doing today?\n\n..."
8251,TYPE 1 DIABETES MELLITUS WITH UNSPECIFIED COMP...,### Medical Note\n\n**1. Subjective:**\n\n**Ch...,"[doctor]: Good morning, how are you doing toda..."
6602,"HYDROCELE, UNSPECIFIED",**1. Subjective:**\n\n**Chief Complaint (CC):*...,"[doctor]: Hello, how are you doing today?\n\n[..."

In [12]:
print(sample_df["Polished Note"][3310])

**1. Subjective:**

**CHIEF COMPLAINT**

Ongoing fatigue, joint pain, and low-grade fever.

**HISTORY OF PRESENT ILLNESS**

The patient, named Emily Johnson, is a 45-year-old Caucasian female with a known history of rheumatoid arthritis and autoimmune thyroiditis who presents for a follow-up visit. She reports experiencing moderate fatigue, joint pain, and low-grade fever for the past two months. Symptoms are persistent and occur daily, significantly impacting her daily activities, making it difficult for her to perform tasks both at home and work. She is currently on medical leave due to these symptoms.

The patient states that her sleep quality is poor, often waking up multiple times during the night. She follows a balanced diet with no specific restrictions and does not use tobacco or drugs. Alcohol consumption is occasional and limited to social settings. Due to joint pain, her physical activity is limited, but she enjoys reading and gardening when her symptoms allow.

The patient is compliant with her current medications, including Methotrexate 15 mg weekly and Levothyroxine 100 mcg daily. She has a documented allergy to penicillin. Her family history is significant for her mother having systemic lupus erythematosus.

**REVIEW OF SYSTEMS**

- General: Reports moderate fatigue and low-grade fever.
- Musculoskeletal: Reports joint pain and swelling in hands and knees.
- Sleep: Poor sleep quality, frequent awakenings at night.
- Respiratory: No cough or shortness of breath.
- Cardiovascular: No chest pain or palpitations.
- Gastrointestinal: No nausea, vomiting, or abdominal pain.
- Neurological: No headaches or vision changes.
- Endocrine: Stable with current thyroid medication.

**2. Objective:**

**VITAL SIGNS**

- Blood Pressure: 125/80 mmHg
- Heart Rate: 78 bpm
- Respiratory Rate: 16 bpm
- Temperature: 99.1°F

**PHYSICAL EXAMINATION**

- General: Alert, no acute distress.
- Skin: No rashes or lesions.
- HEENT: Normal.
- Cardiovascular: Regular rate and rhythm, no murmurs.
- Respiratory: Clear to auscultation bilaterally.
- Abdominal: Soft, non-tender, no organomegaly.
- Musculoskeletal: Tenderness in bilateral hands and knees, mild swelling in both ankles, reduced range of motion.
- Neurological: No focal deficits.

**3. Assessment:**

The patient is a 45-year-old female with a history of rheumatoid arthritis and autoimmune thyroiditis presenting with persistent fatigue, joint pain, and low-grade fever. Her symptoms have been ongoing for two months and are impacting her daily functioning.

Differential diagnosis includes:
- Flare of rheumatoid arthritis
- Potential development of an additional autoimmune condition, such as systemic lupus erythematosus (given family history)
- Thyroid dysfunction
- Infection

**4. Plan:**

1. **Medications:**
   - Continue Methotrexate 15 mg weekly.
   - Continue Levothyroxine 100 mcg daily.

2. **Testing:**
   - Await results of ANA, RF, anti-dsDNA, and serum immunoglobulins.
   - Consider additional thyroid function tests (TSH, free T4).

3. **Symptom Management:**
   - Introduce low-dose prednisone (5 mg daily) temporarily to manage joint pain and inflammation.
   - Recommend use of NSAIDs (e.g., ibuprofen 200 mg as needed) for additional pain relief.

4. **Lifestyle Modifications:**
   - Encourage gentle, low-impact exercises like stretching and swimming.
   - Recommend sleep hygiene measures to improve sleep quality.

5. **Follow-Up:**
   - Schedule a follow-up visit in 4 weeks to review lab results and assess symptom progression.
   - Advise patient to report any new or worsening symptoms immediately.

6. **Patient Education and Counseling:**
   - Explained the potential for a flare of rheumatoid arthritis and the possibilities of additional autoimmune conditions.
   - Discussed the importance of medication adherence and regular monitoring.

Patient understands and agrees with the proposed plan.

In [7]:
sample_df.to_csv("/Users/ahmadrezaie/2_My_papers/Synthetic_Data_Gen/data/output/notes_dial_pairs/phase_2_to_12_combined/sample_data_filtered.csv",sep="|")