In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

our_data= pd.read_csv("/h/ahmad/SynthDataGen/Synthetic_Data_Gen/data/output/notes_onVector/phase_2_to_12_combined/total_data.csv", sep="|")
filtered_df= our_data[["Disease Description", "Polished Note", "Role", "polished_dial"]]

icd10_df= pd.read_csv("/h/ahmad/SynthDataGen/Synthetic_Data_Gen/data/input/IQVIA/IQVIA_cleaned.csv", sep= "|")

merged_df = filtered_df.merge(icd10_df[['ICD10_desc', 'ICD10']], 
                              left_on='Disease Description', 
                              right_on='ICD10_desc', 
                              how='left')

# Drop the auxiliary 'ICD10_desc' column
merged_df.drop('ICD10_desc', axis=1, inplace=True)

# Drop duplicates to ensure no extra rows are added
merged_df = merged_df.drop_duplicates(subset=['Disease Description', 'Role', 'Polished Note', 'polished_dial'])

# Reorder the columns as per the required order
reordered_df = merged_df[['ICD10', 'Disease Description', 'Role', 'Polished Note', 'polished_dial']]

In [2]:
filtered_df

,Disease Description,Polished Note,Role,polished_dial
0,PAIN IN LEFT KNEE,**1. Subjective:**\n\n **Chief Complaint (CC...,Orthopedic Specialist,[doctor]: Hello! It’s good to see you today. H...
1,PAIN IN LEFT KNEE,**1. Subjective:**\n\n - **Chief Complaint (...,General Physician,"[doctor] Hi there, how are you today?\n\n[pati..."
2,PAIN IN LEFT KNEE,**1. Subjective:**\n\n**Chief Complaint (CC):*...,Family Medicine Physician,"[doctor] Good morning, how are you doing today..."
3,PAIN IN LEFT KNEE,**1. Subjective:**\n\n**Chief Complaint (CC):*...,Orthopedic Specialist,[doctor] Good morning! How are you feeling tod...
4,PAIN IN LEFT KNEE,#####\n**1. Subjective:**\n\n**Chief Complaint...,Orthopedic Specialist,"[doctor]: Hello Mr. Doe, how are you doing tod..."
...,...,...,...,...
10030,CANDIDAL ESOPHAGITIS,#####\n**1. Subjective:**\n \n**Chief Compla...,Gastroenterologist,[doctor]: Good morning. How are you doing toda...
10031,CANDIDAL ESOPHAGITIS,### Gastroenterologist Medical Note\n\n#### 1....,Gastroenterologist,"**Doctor:** Hi there, how are you doing today?..."
10032,CANDIDAL ESOPHAGITIS,**1. Subjective:**\n\n**Chief Complaint (CC):*...,Gastroenterologist,"[doctor]: Hi Mr. Harris, how are you doing tod..."
10033,CANDIDAL ESOPHAGITIS,#####\n**1. Subjective:**\n**Chief Complaint (...,Role not found in the first 5 lines.,"[doctor]: Good morning, Ms. Lee. How are you d..."
10034,CANDIDAL ESOPHAGITIS,**1. Subjective:**\n\n**Chief Complaint (CC):*...,Gastroenterologist,[doctor]: Good morning. How are you doing toda...

In [3]:
reordered_df

,ICD10,Disease Description,Role,Polished Note,polished_dial
0,M25562,PAIN IN LEFT KNEE,Orthopedic Specialist,**1. Subjective:**\n\n **Chief Complaint (CC...,[doctor]: Hello! It’s good to see you today. H...
1,M25562,PAIN IN LEFT KNEE,General Physician,**1. Subjective:**\n\n - **Chief Complaint (...,"[doctor] Hi there, how are you today?\n\n[pati..."
2,M25562,PAIN IN LEFT KNEE,Family Medicine Physician,**1. Subjective:**\n\n**Chief Complaint (CC):*...,"[doctor] Good morning, how are you doing today..."
3,M25562,PAIN IN LEFT KNEE,Orthopedic Specialist,**1. Subjective:**\n\n**Chief Complaint (CC):*...,[doctor] Good morning! How are you feeling tod...
4,M25562,PAIN IN LEFT KNEE,Orthopedic Specialist,#####\n**1. Subjective:**\n\n**Chief Complaint...,"[doctor]: Hello Mr. Doe, how are you doing tod..."
...,...,...,...,...,...
10235,B3781,CANDIDAL ESOPHAGITIS,Gastroenterologist,#####\n**1. Subjective:**\n \n**Chief Compla...,[doctor]: Good morning. How are you doing toda...
10236,B3781,CANDIDAL ESOPHAGITIS,Gastroenterologist,### Gastroenterologist Medical Note\n\n#### 1....,"**Doctor:** Hi there, how are you doing today?..."
10237,B3781,CANDIDAL ESOPHAGITIS,Gastroenterologist,**1. Subjective:**\n\n**Chief Complaint (CC):*...,"[doctor]: Hi Mr. Harris, how are you doing tod..."
10238,B3781,CANDIDAL ESOPHAGITIS,Role not found in the first 5 lines.,#####\n**1. Subjective:**\n**Chief Complaint (...,"[doctor]: Good morning, Ms. Lee. How are you d..."
10239,B3781,CANDIDAL ESOPHAGITIS,Gastroenterologist,**1. Subjective:**\n\n**Chief Complaint (CC):*...,[doctor]: Good morning. How are you doing toda...

In [4]:
train_df, test_df = train_test_split(reordered_df, test_size=0.15, random_state=96)

# Optionally, you can reset the index of both DataFrames if needed
train_df = train_df.reset_index(drop=True)
test_df = test_df.reset_index(drop=True)


print(len(train_df))
print(len(test_df))

8529
1506

In [6]:
train_df.to_csv("/h/ahmad/SynthDataGen/Synthetic_Data_Gen/code/benchmarking/dataset/train.csv", sep="|")
test_df.to_csv("/h/ahmad/SynthDataGen/Synthetic_Data_Gen/code/benchmarking/dataset/test.csv", sep= "|")