This notebook contains medical note generation from approach 1: Metadata --> Note --> Dialogue

## Imports

In [1]:
import pandas as pd
import datetime
import openai
from datetime import datetime
import os
import csv
from openai import OpenAI
import random

## Classes and functions

In [2]:
# provides samples from Aci Bench dataset

class AciExampleProvider:
    def __init__(self, data_file, sample_size=15):
        self.data_file = data_file
        self.sample_size = sample_size
        self.meta_and_note = ""

    def sample_meta_and_note(self):
        """
        Samples metadata and note content from Aci.
        """
        try:
            aci_df = pd.read_csv(self.data_file)
            aci_df.rename(columns={'cc': 'chief_complaint'}, inplace=True)
            aci_data = aci_df[aci_df['dataset'] == 'aci']
            aci_data = aci_data.sample(n=self.sample_size)

            example_number = 1
            for index, row in aci_data.iterrows():
                metadata = row[-7:]
                note = row['note']

                self.meta_and_note += f"Example {example_number}:\n\nMetadata:\n"
                for col, value in metadata.items():
                    self.meta_and_note += f" {col}: {value}, "
                self.meta_and_note = self.meta_and_note.rstrip(', ')
                self.meta_and_note += f"\n\n\n\nNote:\n{note}\n\n{'*'*75}\n\n"
                example_number += 1

        except Exception as e:
            return f"An error occurred while sampling meta and note: {e}"
        
        return self.meta_and_note

    def write_to_file(self, output_file_base):
        """
        Just in case we wanna save the sampled data. 
        Writes the sampled meta and note to a file with a date-stamped filename.
        """
        current_date = datetime.datetime.now().strftime("%d%m")
        output_file = f"{output_file_base}_{current_date}.txt"
        try:
            with open(output_file, 'w') as file:
                file.write(self.meta_and_note)
            return f"Data has been written to {output_file}"
        except Exception as e:
            return f"An error occurred: {e}"

In [3]:

# to open a file and return its content as a string:
def open_file(file_path):
  with open(file_path, "r", encoding = "utf-8") as infile:
    return infile.read()
  

def save_to_csv2(data, base_filename, directory):
    # Ensure the directory ends with a slash
    if not directory.endswith('/'):
        directory += '/'

    # Get the current date in YYYYMMDD format
    current_date = datetime.now().strftime("%Y%m%d")

    # Create the filename with the current date and directory
    filename = f"{directory}{base_filename.split('.')[0]}_{current_date}.csv"

    # Save the data to a CSV file
    with open(filename, mode='w', newline='', encoding='utf-8') as file:
        writer = csv.writer(file)
        writer.writerow(['Diagnosis_Desc', 'Synthetic_Note'])
        for row in data:
            writer.writerow(row)

    print(f"Data has been saved to {filename}")

  
def initialize_openai_client(api_key_file):
    """
    Initialize the OpenAI client with an API key read from a file.

    Args:
    api_key_file (str): The path to the file containing the OpenAI API key.

    Returns:
    openai.Client: An instance of the OpenAI client.
    """
    try:
        with open(api_key_file, 'r') as file:
            api_key = file.read().strip()
        client = openai.Client(api_key=api_key)
        return client
    except Exception as e:
        print(f"An error occurred: {e}")
        return None

## Note Generation:

### Preparations

In [4]:
def generate_text_no_system(PROMPT):
    response = client.chat.completions.create(
        model="gpt-4-1106-preview",
        messages=[
            {"role": "user", "content": PROMPT}
        ],
        temperature=0.7
    )
    return response.choices[0].message.content.strip()

In [5]:
def generate_text_with_system(PROMPT):
    response = client.chat.completions.create(
        model="gpt-4-1106-preview",
        messages=[
            {
            "role": "system",
            "content": ""
            },
            {"role": "user", "content": PROMPT}
        ],
        temperature=0.7
    )
    return response.choices[0].message.content.strip()

In [6]:
# In case we saved the samples from Aci into a csv and want to read it, this is useful
# Read the contents of the example file into a variable
''' 
with open('/Users/ahmadrezaie/DalPhD/Research/note_taking/Data/sample_note_and_dialog.txt', 'r') as file:
    examples = file.read()

'''

" \nwith open('/Users/ahmadrezaie/DalPhD/Research/note_taking/Data/sample_note_and_dialog.txt', 'r') as file:\n    examples = file.read()\n\n"

In [7]:
# icd distibution data:

icd_df = pd.read_csv("/Users/ahmadrezaie/DalPhD/Research/note_taking/Data/IQVIA/ICD10count_diag_admit.csv")

In [8]:
# List of inclusive names from different races
names = ["Aisha", "Carlos", "Wei", "Fatima", "John", "Olga", "Dev", "Yuki", "Nia", "Samuel", "Chen", "Irina", "Mohammed", "Leila", "Raj", "Lena", "Hiroshi", "Tanya", "Luis", "Zara"]


# initializing openAI:
client = initialize_openai_client("/Users/ahmadrezaie/DalPhD/Research/note_taking/Code/OpenAIkey.txt")

### Note Generation Loop

In [ ]:
# propmpt:

PROMPT= """ I am giving you some examples of doctor's notes from visiting a patient. The notes re generated from some metadata.
            The examples contain the metadata and the correscponding note.
            Your task is to generate a similar structure note but for a differrent medical condition. Please try your
            best. It is very important for the patients and their families.
            Please have in mind that you are given the chief_complaint in the examples, but I will give you the 
            "ICD-10_code_description" of a disease and you should infer the "chief_complaint" yourself to generate the note. 
            Also, please consider a secondary complaint yourself based on what you think is relevant and approprite. 
            Here is the new metadata:
            "ICD-10_code_description: "{icd_description}", doctor_name: {doctor_name}, patient_gender: {gender}, patient_age: {age}, patient_firstname: {first_name}, patient_familyname: {family_name}
            Here are the example: {example}
            """

In [ ]:
all_generated_notes = []

try:
        for i, row in icd_df.head(10).iterrows():
            # Randomly select gender, age, and names
            gender = random.choice(["male", "female"])
            age = str(random.randint(18, 75))
            first_name = random.choice(names)
            family_name = random.choice(names)
            doctor_name = random.choice(names)  

            modified_prompt = PROMPT.format(
                icd_description=row['diagnosis_desc'],
                doctor_name=doctor_name,
                gender=gender,
                age=age,
                first_name=first_name,
                family_name=family_name,
                example=examples
                )

            synthetic_note = generate_text_no_system(modified_prompt)
            if i <= 2:
                print(row['diagnosis_desc'], synthetic_note)

            all_generated_notes.append([row['diagnosis_desc'], synthetic_note])
            print(f"Completed API call {i + 1}")
            
except KeyboardInterrupt:
        print("\nKeyboard interrupt detected. Saving partial data to the CSV file...")

finally:
        save_to_csv2(all_generated_notes, "meta_to_note_random_age_gender_sample_examples.csv", "/Users/ahmadrezaie/DalPhD/Research/note_taking/Data/")

## Check the rersults

print()

# Further tests:

## With system prompt, no Aci data used:

In [6]:
# initializing openAI:
client = initialize_openai_client("/Users/ahmadrezaie/DalPhD/Research/note_taking_v2/data/input/OpenAIkey.txt")

An error occurred: [Errno 2] No such file or directory: '/Users/ahmadrezaie/DalPhD/Research/note_taking_v2/data/input/OpenAIkey.txt'

### Single LLM doctor

In [7]:
system_prompt =  "Assume you are a very experienced family physician doctor and you are conducting a research. The research project is to generate synthetic medical notes from doctor-patient conversations. \nThe notes must in this format:\n\n1. Subjective: This section includes the patient's own description of their symptoms and complaints.\n\n2. Objective: This section includes observations and data gathered by the family physician, such as vital signs, physical examination findings, and test results.\n\n3. Assessment: This section includes the family physician's evaluation of the patient's condition, including a diagnosis or differential diagnosis.\n\n4. Plan: This section includes the family physician's recommendations for treatment, management, and follow-up. \n\n\nThe notes must contain these variables:\n\n1) Medical Outcome: Like diagnosis, prescribed treatment, follow-up recommendations, referral to specialists, referral to further tests or imaging, medication adjustment, lifestyle change (sleep, diet, exercise, tobacco use, alcohol use)\n\n\n2) Medical History: Like previous diagnoses, family medical history, medication history, allergies, and chronic conditions.\n\n3) Symptom Description: Like severity, duration, associated symptoms, frequency, and impact on daily activities.\n\n4) Patient’s self-reported habits and lifestyle: Sleep, diet, exercise, tobacco use, alcohol consumption, drug use, recreational activities.\n\n5) Demographic Information: Like age, gender, ethnicity, socio-economic status, education level, health literacy, and job status.\n\n6) Patient's Behavior: Like the patient's cooperation with medical advice\n\n7) Geographical Location: Like Big city vs small city, rural vs urban, pollution and environmental health risks, neighborhood type- eg if impoverished or affluent, well-served by transit, food desert, etc.\n\n8) Clinical Setting: Like hospitals, clinics, telemedicine, community health services, urgent care centers, research facilities, school health services, private practice, and specialty clinics.\n\n9) Type of Encounter: Like initial consultation, follow-up, emergency visit, routine check-up, chronic disease management (regular appointments to manage long-term health conditions like diabetes, heart disease, or chronic pain), preventive health screening.\n\n10) Treatment Disparities: There may be a tendency to offer less aggressive treatment or fewer options due to assumptions about compliance or ability to pay.\n\n11) Native or Non-Native English Speaking Patient.\n\nThe user will give you the ICD-10 description of the disease and you should generate a note in the format mentioned above. "

def generate_note(condition):
        response = client.chat.completions.create(
        model="gpt-4-1106-preview",
        messages=[
            {
                "role": "system",
                "content": system_prompt
            },
            {
                "role": "user",
                "content": condition
            }
        ],
        temperature=0.68,
        max_tokens=4052,
        top_p=1,
        frequency_penalty=0,
        presence_penalty=0
        )
        return response.choices[0].message.content

In [13]:
note = generate_note("Hypertention")
print(note)

# ask the  model to write down the gist of the scenario, and the values of variables its going to use. Also, write down
# every medical fact its going to use. It will make it easier to evaluate in the future and make it easier to ensure the variety of notes for 
# a medical condition. The scenarios are shorter to feed to the model iteratively.

Subjective:
Mr. Johnson, a 52-year-old African American male, presents with complaints of occasional headaches and dizziness over the past month. He describes the headaches as moderate in intensity, mostly occurring in the late afternoon, and sometimes accompanied by a sensation of pulsating in his temples. He denies any associated nausea or visual disturbances. Mr. Johnson reports the symptoms have been impacting his concentration at work as an accountant. He has a history of hypertension diagnosed two years ago. His father also had hypertension. He's currently on hydrochlorothiazide but admits to missing doses occasionally.

Objective:
Vital Signs: BP 162/98 mmHg, HR 78 bpm, RR 16 breaths/min, Temp 98.6°F (37°C).
Physical Examination: Auscultation reveals no abnormal heart or lung sounds. BMI is 29, indicating overweight status. No edema is noted in extremities. Fundoscopic exam shows no signs of papilledema or vascular changes.
Tests: Previous lab results from 3 months ago showed normal renal function and electrolytes.

Assessment:
Mr. Johnson's symptoms and elevated blood pressure readings are consistent with poorly controlled hypertension. There is a family history of hypertension, which increases his risk. The lack of adherence to his medication regimen could be contributing to suboptimal control of his blood pressure.

Plan:
1. Reinforce the importance of medication adherence for hydrochlorothiazide and consider a daily medication organizer.
2. Initiate amlodipine 5 mg once daily to improve blood pressure control.
3. Lifestyle modifications: Advise a low-sodium diet, regular aerobic exercise (30 minutes a day, most days of the week), and weight reduction with a goal of achieving a BMI within the normal range.
4. Schedule a follow-up visit in 4 weeks to re-evaluate blood pressure and discuss the effectiveness of the new medication regimen.
5. Encourage home blood pressure monitoring twice daily and to keep a log of the readings.
6. Refer to a dietitian for assistance with meal planning and weight loss strategies.

Variables:
1) Medical History: Hypertension, family history of hypertension, on hydrochlorothiazide.
2) Symptom Description: Moderate intensity headaches, dizziness, duration of one month, impacting work.
3) Patient’s self-reported habits and lifestyle: Sedentary job, occasional missed medication, does not mention diet or exercise habits, no tobacco, alcohol, or drug use reported.
4) Demographic Information: 52-year-old, African American male, accountant, appears to have moderate health literacy.
5) Patient's Behavior: Partially non-adherent to medication regimen, but cooperative with medical advice during the consultation.

In [8]:
note = generate_note("Hypertention")
print(note)

Subjective:
A 53-year-old male patient presents for a routine follow-up appointment complaining of occasional headaches and dizziness over the past two months. He reports that these symptoms often occur in the morning and sometimes after physical exertion. The patient notes that his home blood pressure readings have been higher than usual, averaging around 145/95 mmHg. He denies chest pain, palpitations, or dyspnea. He mentions his father had hypertension and his mother has type 2 diabetes. The patient is a long-term smoker and admits to a sedentary lifestyle with a high-sodium diet.

Objective:
The patient is alert and oriented. Blood pressure is measured at 148/92 mmHg in the office. Heart rate is regular at 78 bpm, and respiratory rate is 16 breaths per minute. BMI is calculated at 30, indicating obesity. Physical examination reveals no additional abnormalities. No edema is noted. Fundoscopic exam is unremarkable with no signs of hypertensive retinopathy. Laboratory tests including a complete blood count, basic metabolic panel, and lipid profile are ordered.

Assessment:
The patient is diagnosed with primary hypertension. The absence of secondary symptoms and negative family history for kidney disease make secondary causes less likely. His lifestyle factors and family history of hypertension contribute to his condition.

Plan:
The patient will be started on a low-dose thiazide diuretic, hydrochlorothiazide, and will be counseled on lifestyle modifications. Dietary changes will include a reduction in sodium intake and a DASH (Dietary Approaches to Stop Hypertension) diet. An exercise regimen of 30 minutes of moderate-intensity activity five days a week is recommended. The patient is strongly advised to quit smoking and is referred to a smoking cessation program. A follow-up appointment is scheduled in four weeks to reevaluate blood pressure and treatment efficacy. The patient is encouraged to monitor his blood pressure at home and keep a log. Education on the importance of medication adherence and potential complications of uncontrolled hypertension is provided. A referral to a dietitian is made for additional support in lifestyle changes.

In [10]:
# main loop to ask for medical condition, then generate notes:
import datetime

# Get the current date and format it as a string
current_date = datetime.datetime.now().strftime("%Y-%m-%d")

# Create the filename with the current date
path = "/Users/ahmadrezaie/DalPhD/Research/note_taking_v2/data/output"
filename = f"{path}/medical_notes_{current_date}.csv"

# Main loop
with open(filename, 'w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    
    # Write the prompt at the top of the file
    writer.writerow(["Prompt: " + system_prompt])
    
    # Write column headers
    writer.writerow(["Medical_Condition", "Note"])

    while True:
        # Ask the user for a medical condition
        condition = input("Enter a medical condition (or type 'exit' to stop): ").strip()
        
        # Check if the user wants to exit
        if condition.lower() == 'exit':
            break
        
        # Generate medical notes for the given condition
        medical_notes = generate_note(condition)

        # Write the condition and notes to the CSV file
        writer.writerow([condition, medical_notes])
        print("Note saved to CSV.")

print("Exiting the program.")

Note saved to CSV.
Note saved to CSV.
Note saved to CSV.
Note saved to CSV.
Note saved to CSV.
Note saved to CSV.
Note saved to CSV.
Note saved to CSV.
Note saved to CSV.
Note saved to CSV.
Note saved to CSV.
Note saved to CSV.
Note saved to CSV.
Note saved to CSV.
Note saved to CSV.
Note saved to CSV.
Note saved to CSV.
Note saved to CSV.
Exiting the program.

The model did not get it when I asked to generate 5 different notes for a single condition. 

How to make sure to make the notes as different as possible:

1) Use Prompt Modifiers: Integrate modifiers in your prompts to guide the generation of diverse notes. For example:

"Write a medical note focusing on the treatment plan for [condition]."
"Create a brief note emphasizing the diagnostic process for a patient with [condition]."

We can use "Medical Outcome" control variable for this. Like:
Write a medical note focusing on "[medicaloutcome_1]" for [condition].
Write a medical note focusing on "[medicaloutcome_2]" for [condition].
Write a medical note focusing on "[medicaloutcome_1]" and "[medicaloutcome_2]" for [condition].


2) Controlled Randomness: Introduce controlled randomness. You could randomize certain elements of your prompt (like patient age, symptoms, or background) using your own code before sending it to the API.

3) Sequential Requests with Memory: Make sequential requests where each new request builds upon or differs from the previous ones. You can maintain a 'memory' or log of past requests and guide the API to generate notes that are different. 


4) Feedback Loop: Use a feedback loop where the output of the previous generation influences the next prompt. This could be automated or manual, where you assess the diversity and tweak the prompts accordingly.
I am using the cobmination of 3 and 4:

It means we can iteratively add the model's previous generated notes to the input prompt and ask to make it different thn this one. 
Look at this link also: https://community.openai.com/t/function-calling-with-memory/307051 


5) Having another LLM as "Judge" to check if the generated notes are different.

Test this approach:

Have 2 LLMs; The doctor and the Judge. The doctor first generates the scenario (the values pf each variable that it is going to use to generate the notes) and pass it to the Judge. Judge then compares it with the previous scenarios (combinations of variables) for the same ICD-10. If at least 4 out of 11 variables are differernt, then the Judge outputs "Go", and the doctor proceeds to generate the note. If the condition is not met, the Judge outputs "No Go", and then the doctor should revise the scenario to pass the condition. 
We can test this approach for 15 ICD-10 codes, generating 15 notes for each. Then, check the similarity score (with some embeding approach) between the notes from the same ICD-10 codes to test if the approach works.

### Three LLM setting: Scenario provider, Judge, and note generator:

Test this approach:

Have 2 LLMs; The doctor and the Judge. The doctor first generates the scenario (the values pf each variable that it is going to use to generate the notes) and pass it to the Judge. Judge then compares it with the previous scenarios (combinations of variables) for the same ICD-10. If at least 4 out of 11 variables are differernt, then the Judge outputs "Go", and the doctor proceeds to generate the note. If the condition is not met, the Judge outputs "No Go", and then the doctor should revise the scenario to pass the condition. 
We can test this approach for 15 ICD-10 codes, generating 15 notes for each. Then, check the similarity score (with some embeding approach) between the notes from the same ICD-10 codes to test if the approach works.

##### implementation

In [4]:
model = "gpt-4-1106-preview"
temperature=1
max_tokens=4052
top_p=1
frequency_penalty=0
presence_penalty=0


doctor_scenario_generator_system_prompt ="Assume you are a very experienced physician and you are conducting research. The research project is to generate synthetic medical notes from doctor-patient conversations. \n\nThe notes must contain these variables:\n\n1) Medical Outcome: Like diagnosis, prescribed treatment, follow-up recommendations, referral to specialists, referral to further tests or imaging, medication adjustment, lifestyle change (sleep, diet, exercise, tobacco use, alcohol use). If it is prescribing medication, details should be included like dose, units, frequency, duration, quantity, quantity type (like tablets, etc.), and route (like oral or injected). If it is a referral, it should include details like the reason for the referral, the specialty, and the doctor's name. If it is an order for blood work, it should include details like if it is for biochemistry, hematology, immunology, microbiology, viral hepatitis, vitamin D, prostate-specific antigen, or anything else that suits the scenario. You need to be very specific. If it's an order for imaging, it should include details like the modality of the imaging and the area of the body. For example, if it is ultrasound, it can be an order for Abdominal, Thyroid, Musculoskeletal, Sonohysterogram, Sonohysterogram, Biophysical Profile(BPP), Scrotal, G.U. Tract - Kidneys-Bladder(Prostate), or anything else as it suits the scenario. Try to be very specific. \n\n\n2) Medical History: Like previous diagnoses, family medical history, medication history, allergies, and chronic conditions.\n\n3) Symptom Description: Like severity, duration, associated symptoms, frequency, and impact on daily activities.\n\n4) Patient’s self-reported habits and lifestyle: Sleep, diet, exercise, tobacco use, alcohol consumption, drug use, recreational activities.\n\n5) Demographic Information: Like age, gender, ethnicity, socio-economic status, education level, health literacy, and job status.\n\n6) Patient's Behavior: Like the patient's cooperation with medical advice\n\n7) Geographical Location: Like Big city vs small city, rural vs urban, pollution and environmental health risks, neighborhood type- eg if impoverished or affluent, well-served by transit, food desert, etc.\n\n8) Clinical Setting: Like hospitals, clinics, telemedicine, community health services, urgent care centers, research facilities, school health services, private practice, and specialty clinics.\n\n9) Type of Encounter: Like initial consultation, follow-up, emergency visit, routine check-up, chronic disease management (regular appointments to manage long-term health conditions like diabetes, heart disease, or chronic pain), preventive health screening.\n\n10) Treatment Disparities: There may be a tendency to offer less aggressive treatment or fewer options due to assumptions about compliance or ability to pay.\n\n11) Native or Non-Native English Speaking Patient.\n\n12) Physical exams: Any physical exams that are suitable for the scenario.\n\n13) Investigation/Test results: Like any tests that have been done for the patient while visiting. The results could be ready and reviewed in the scenario or could be awaiting. If awaiting, you need to be very specific about what type of tests have been done. For example, if it is X-ray, you need to incude the details mentioned abve about the imaging.\n\nThe user will give you the ICD-10 description of the disease. The diagnosis in the scenario must be the ICD-10 description. First, you select a role for yourself. You can be a Family Medicine Physician, a General physician, or a specialist with different specialties. Select the role based on the ICD-10 description and output it with the keyword 'ROLE:'. Second, you must come up with a scenario and list all the values of the variables you want to use in the scenario, and show it to the user. Do not output any extra text, just your role at the top of the scenario and the list of the values. You should incorporate medication and blood work or imaging requests in the scenarios with the details mentioned above if it suits the scenario. These are artificial and people will not be using it without asking a real doctor. "


doctor_note_generator_system_prompt = "Assume you are a very experienced physician and you are conducting research. The research project is to generate synthetic medical notes from doctor-patient conversations. \nThe notes must be in this format:\n\n1. Subjective: This section includes the patient's own description of their symptoms and complaints.\n\n2. Objective: This section includes observations and data gathered by the physician, such as vital signs, physical examination findings, and test results.\n\n3. Assessment: This section includes the physician's evaluation of the patient's condition, including a diagnosis or differential diagnosis.\n\n4. Plan: This section includes the physician's recommendations for treatment, management, and follow-up. \n\n\nYou will be given a scenario containing your role. Your role can be a Family Medicine Physician, a General physician, or a specialist with different specialties. You must generate the note following exactly the scenario. All the notes you generate must be in the format mentioned above. All the tests ordered (including blood work or imaging) must be in the 'Plan' section. "

judge_system_pormpt = "Assume you are a very experienced physician and you are conducting research. The research project is to generate synthetic medical notes from doctor-patient conversations. \nYou have a coworker that works with you on the project. You have different roles. \nThe coworker provides you with the scenario they are going to write notes with. Your job is to judge whether the scenario is approved or not based on the conditions I provided below. \n\nThe scenarios have 13 variables. \n \n1) Medical Outcome\n\n2) Medical History\n\n3) Symptom Description\n\n4) Patient’s self-reported habits and lifestyle\n\n5) Demographic Information\n\n6) Patient's Behavior\n\n7) Geographical Location\n\n8) Clinical Setting\n\n9) Type of Encounter\n\n10) Treatment Disparities\n\n11) Native or Non-Native English Speaking Patient.\n\n12) Physical exams: Any physical exams that are suitable for the scenario.\n\n13) Investigation/Test results: Like any tests that have been done for the patient while visiting. The results could be ready and reviewed in the scenario or could be awaiting.\n\n\nYou have to check three conditions and then decide to approve or deny the scenario:\n\na) A pair-wise comparison of the values of the variables. You need to check if at least 5 out of 13 of the values of the variables in the scenario are different from the previously approved scenarios.\n\nb) You need to check if the scenario is medically correct in terms of symptoms, tests, diagnosis, and treatment. \n\nc) You need to check if the scenario is plausible or not.\n\nFirst, check condition \"a\". If it is not met, the scenario is rejected and you do not need to check conditions \"b\" and \"c\". \n\nIf the scenario passes these three conditions, then say \"Go\". If not, you say \"NoGo\".  In the case that there is no scenario previously approved, you should only check conditions \"b\" and \"c\".\n\n\"Go\" or \"No Go\" must be your only words. "

note_polisher_system_prompt =  "Assume you are a very experienced physician and you are conducting research. The research project is to generate synthetic medical notes from doctor-patient conversations. \nThe notes must be in this format:\n\n1. Subjective: This section includes the patient's own description of their symptoms and complaints.\n\n2. Objective: This section includes observations and data gathered by the physician, such as vital signs, physical examination findings, and test results.\n\n3. Assessment: This section includes the physician's evaluation of the patient's condition, including a diagnosis or differential diagnosis.\n\n4. Plan: This section includes the physician's recommendations for treatment, management, and follow-up. \n\n\nYou will be given a note. Your task is to polish the note and make sure the information is placed correctly in the relevant section.  You cannot add or remove any information, except where you have been given permission.\n\nMake sure of these:\n\na) If the doctor is ordering an imaging or bloodwork to be done, it must come under the Plan\" section. But if it is already done, it can come in other sections. \n\nb) If the doctor is prescribing a medication or renewing a medication, changing doses, etc., it must be under the \"Plan\" section. \n\nc) Referrals must come under the \"Plan\" section. The referral must contain the reason for referral, the specialty, and the doctor's name. If any part is missing, add it. You can choose any appropriate name, do not stick with one name.\n\nd) Patients' must have names. If there is no name, add it. You can choose any appropriate name, do not stick with one name.\n\n\nJust output the revised note, not anything else. \n"

In [7]:
# initializing openAI:
client = initialize_openai_client("/h/ahmad/SynthDataGen/Synthetic_Data_Gen/data/input/OpenAIkey.txt")

In [7]:

def doctor_generate_scenario(condition):
        scenario_response = client.chat.completions.create(
        model=model,
        temperature = temperature,
        max_tokens = max_tokens,
        top_p = top_p,
        frequency_penalty = frequency_penalty,
        presence_penalty = presence_penalty,
        messages=[
            {
                "role": "system",
                "content": doctor_scenario_generator_system_prompt
            },
            {
                "role": "user",
                "content": condition
            }
        ]
        )
        return scenario_response.choices[0].message.content



def doctor_generate_note(scenario):
        note_response = client.chat.completions.create(
        model=model,
        temperature = temperature,
        max_tokens = max_tokens,
        top_p = top_p,
        frequency_penalty = frequency_penalty,
        presence_penalty = presence_penalty,
        messages=[
            {
                "role": "system",
                "content": doctor_note_generator_system_prompt
            },
            {
                "role": "user",
                "content": scenario
            }
        ]
        )
        return note_response.choices[0].message.content


def judge_evaluate_scenario(scenario, conversations_memory):
    # Add system prompt and user scenario to memory
        conversations_memory += [
        {"role": "user", "content": scenario}
        ]
        evaluation_response = client.chat.completions.create(
        model=model,
        temperature = temperature,
        max_tokens = max_tokens,
        top_p = top_p,
        frequency_penalty = frequency_penalty,
        presence_penalty = presence_penalty,
        messages=conversations_memory
        )
        # Accessing the last message's content correctly
        latest_message = evaluation_response.choices[0].message.content
        print("Latest message is: ", latest_message)
        decision = latest_message.split()[-1]  # Extract the last word

        # Update memory with the model's latest response
        conversations_memory.append({"role": "assistant", "content": latest_message})
        print(decision)
        print(conversations_memory)
        print("len of conversation_momory is: ",len(conversations_memory))
        return decision

In [8]:
def polish(note):
        note_response = client.chat.completions.create(
        model=model,
        temperature = temperature,
        max_tokens = max_tokens,
        top_p = top_p,
        frequency_penalty = frequency_penalty,
        presence_penalty = presence_penalty,
        messages=[
            {
                "role": "system",
                "content": note_polisher_system_prompt
            },
            {
                "role": "user",
                "content": note
            }
        ]
        )
        return note_response.choices[0].message.content

In [9]:
# a function to extract the "ROLE" from the scenario:

import re

def extract_role(text):
    # take the first 5 lines
    first_5_lines = '\n'.join(text.splitlines()[:5])
    # Define the regular expression pattern to find "ROLE:" (in any capitalization) followed by any characters until a line break
    pattern = r"ROLE: (.+?)\n"

    match = re.search(pattern, first_5_lines, re.IGNORECASE)
    # If a match is found, return the group which matches the role description
    if match:
        return match.group(1)
    else:
        # Return None or an appropriate message if "ROLE:" is not found within the first 5 lines
        return "Role not found in the first 5 lines."

In [10]:
def generate_medical_notes(disease_description, notes_count):
    approved_notes = []
    rejected_scenarios = []
    judge_conversations_memory = [{"role": "system", "content": judge_system_pormpt}]

    try:
        while True:
            scenario = doctor_generate_scenario(disease_description)
            decision = judge_evaluate_scenario(scenario, judge_conversations_memory)
            if decision == "Go" or decision == "Go.":
                role = extract_role(scenario)
                note = doctor_generate_note(scenario)
                polished_note = polish(note)
                approved_notes.append({"Disease Description": disease_description, "Scenario": scenario, "Note": note, "Polished Note": polished_note , "Role": role })
            else:
                rejected_scenarios.append({"Disease Description": disease_description, "Scenario": scenario, "Note": "Rejected", "Polished Note": "Rejected", "Role": "Rejected"})
            
            # Respecting the number of needed approved notes
            if len(approved_notes) >= notes_count:
                break

    except Exception as e:
        print(f"An error occurred during note generation: {e}")
    
    finally:
        # Combine the results
        results = approved_notes + rejected_scenarios
        df = pd.DataFrame(results)
    return pd.DataFrame(results)

In [11]:
import datetime
current_date = datetime.datetime.now().strftime("%Y-%m-%d")

# Create the filename with the current date
path = "/Users/ahmadrezaie/papers/Synthetic_Data_Gen/data/output"

In [ ]:
""" 
disease_description = "Shortness of Breath"
notes_count = 5
df = generate_medical_notes(disease_description, notes_count)

# Save to CSV
df.to_csv(filename, index=False)
"""

In [12]:
sample_five_icds = ["HERPESVIRAL INFECTION, UNSPECIFIED", "SENSORINEURAL HEARING LOSS, BILATERAL", "CHRONIC VIRAL HEPATITIS C", 
                    "CHRONIC PAIN SYNDROME", "MAJOR DEPRESSIVE DISORDER, RECURRENT SEVERE WITHOUT PSYCHOTIC FEATURES"]

In [13]:
for condition in sample_five_icds:
    disease_description = condition
    filename = f"{path}/{disease_description}doctor_judge_notes_{current_date}_2.csv" 
    notes_count = 5 
    df = generate_medical_notes(disease_description, notes_count)
    df.head()

    # Save to CSV
    #df.to_csv(filename, index=False)

KeyboardInterrupt:

In [72]:
# sampling notes for feedback from physicians

import os

feedback_dir = "/Users/ahmadrezaie/papers/Synthetic_Data_Gen/data/output/for_feedback_round1/after_polish"

# Initialize an empty DataFrame to hold samples
sampled_rows_df = pd.DataFrame()

for filename in os.listdir(feedback_dir):
    if filename.endswith(".csv"):
        file_path = os.path.join(feedback_dir, filename)
        df = pd.read_csv(file_path)
        # Sample one row from the top 5 rows randomly
        sampled_row = df.head(5).sample(1)
        # Append the sampled row to the DataFrame
        sampled_rows_df = pd.concat([sampled_rows_df, sampled_row], ignore_index=True)


sampled_rows_df.to_csv("/Users/ahmadrezaie/papers/Synthetic_Data_Gen/data/output/for_feedback_round1/after_polish/sample_notes.csv", sep="|")
sampled_rows_df

,Disease Description,Scenario,Note,Polished Note,Role
0,"SENSORINEURAL HEARING LOSS, BILATERAL",ROLE: Otologist (Ear Specialist)\n\n- Medical ...,**Medical Note**\n\n**Subjective:**\nThe patie...,**Medical Note**\n\n**Subjective:**\nThe patie...,Otologist (Ear Specialist)
1,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n1) Medical...,Subjective:\nThe 42-year-old female patient pr...,"Subjective:\nThe patient, Emily, a 42-year-old...",Pain Management Specialist
2,CHRONIC VIRAL HEPATITIS C,ROLE: Infectious Disease Specialist\n\n- Medic...,Medical Note:\n\n1. Subjective:\nA 52-year-old...,Medical Note:\n\n1. Subjective:\nA 52-year-old...,Infectious Disease Specialist
3,"MAJOR DEPRESSIVE DISORDER, RECURRENT SEVERE WI...",ROLE: Psychiatrist\n\n1) Medical Outcome: Diag...,"Subjective:\nThe patient, a 38-year-old Caucas...","Subjective:\nThe patient, whom I shall refer t...",Psychiatrist
4,"HERPESVIRAL INFECTION, UNSPECIFIED",ROLE: Infectious Disease Specialist\n\n1) Medi...,Subjective:\nA 29-year-old female presents wit...,"Subjective:\nA 29-year-old female, whom we'll ...",Infectious Disease Specialist

In [1]:
import pandas as pd
df = pd.read_csv("/h/ahmad/SynthDataGen/Synthetic_Data_Gen/data/output/notes_onVector/CHRONIC PAIN SYNDROME_2024-05-15", sep="|")
df

,Disease Description,Scenario,Note,Polished Note,Role
0,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n1) Medical...,**Subjective:** \nThe 45-year-old female patie...,"**Subjective:** \nThe patient, Ms. Jane Doe, a...",Pain Management Specialist
1,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n** Medical...,**Subjective:**\nThe patient is a 45-year-old ...,"**Subjective:**\nThe patient, Jane Doe, a 45-y...",Pain Management Specialist
2,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n1) Medical...,**Subjective:**\nThe patient is a 46-year-old ...,"**Subjective:**\nThe patient, Mrs. Jane Doe, i...",Pain Management Specialist
3,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n1) Medical...,**Subjective:**\nThe patient is a 52-year-old ...,"**Subjective:**\nThe patient, Mrs. Linda Thomp...",Pain Management Specialist
4,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n1) Medical...,**Subjective:**\n\nThe patient is a 45-year-ol...,"**Subjective:**\n\nThe patient, Mrs. Emily Tho...",Pain Management Specialist
5,CHRONIC PAIN SYNDROME,ROLE: Family Medicine Physician\n\n1) Medical ...,**Medical Note:**\n\n**Date:** [Insert Date of...,**Medical Note:**\n\n**Date:** [Insert Date of...,Family Medicine Physician
6,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n1) Medical...,**Subjective:**\nThe patient is a 52-year-old ...,"**Subjective:**\nThe patient, Jane Doe, is a 5...",Pain Management Specialist
7,CHRONIC PAIN SYNDROME,ROLE: Family Medicine Physician\n\n1) Medical ...,**1. Subjective:**\nThe patient is a 45-year-o...,"**1. Subjective:**\nThe patient, Jane Doe, a 4...",Family Medicine Physician
8,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n1) Medical...,**Subjective:**\nThe patient is a 45-year-old ...,"**Subjective:**\nThe patient, Jane Doe, is a 4...",Pain Management Specialist
9,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n1) Medical...,**Subjective:**\nThe patient is a 48-year-old ...,"**Subjective:**\nThe patient, Mrs. Linda Thomp...",Pain Management Specialist
10,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n1) Medical...,**Subjective:**\nThe patient is a 45-year-old ...,"**Subjective:**\nThe patient, Emily Thompson, ...",Pain Management Specialist
11,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\nScenario:\...,**Subjective:**\nThe patient is a 45-year-old ...,"**Subjective:**\nThe patient, Jane Doe, is a 4...",Pain Management Specialist
12,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n1) Medical...,**Subjective:**\nThe patient is a 47-year-old ...,"**Subjective:**\nThe patient, Mr. Johnathan Gr...",Pain Management Specialist
13,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n1) Medical...,"**Subjective:**\nThe patient, a 45-year-old Ca...","**Subjective:**\nThe patient, Jane Doe, a 45-y...",Pain Management Specialist
14,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n1) Medical...,**Subjective:**\nThe patient is a 52-year-old ...,"**Subjective:**\nThe patient, John Doe, is a 5...",Pain Management Specialist
15,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n1) Medical...,Rejected,Rejected,Rejected
16,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n1) Medical...,Rejected,Rejected,Rejected

In [8]:
def get_embedding(text, model="text-embedding-3-small"):
   text = text.replace("\n", " ")
   return client.embeddings.create(input = [text], model=model).data[0].embedding

df = pd.read_csv("/h/ahmad/SynthDataGen/Synthetic_Data_Gen/data/output/notes_onVector/CHRONIC PAIN SYNDROME_2024-05-15", sep="|")
df['embedding'] = df.Scenario.apply(lambda x: get_embedding(x, model='text-embedding-3-small'))
df

,Disease Description,Scenario,Note,Polished Note,Role,embedding
0,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n1) Medical...,**Subjective:** \nThe 45-year-old female patie...,"**Subjective:** \nThe patient, Ms. Jane Doe, a...",Pain Management Specialist,"[-0.005625685676932335, 0.026912622153759003, ..."
1,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n** Medical...,**Subjective:**\nThe patient is a 45-year-old ...,"**Subjective:**\nThe patient, Jane Doe, a 45-y...",Pain Management Specialist,"[-0.015071071684360504, 0.02452823892235756, 0..."
2,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n1) Medical...,**Subjective:**\nThe patient is a 46-year-old ...,"**Subjective:**\nThe patient, Mrs. Jane Doe, i...",Pain Management Specialist,"[0.006586750969290733, 0.025920720770955086, 0..."
3,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n1) Medical...,**Subjective:**\nThe patient is a 52-year-old ...,"**Subjective:**\nThe patient, Mrs. Linda Thomp...",Pain Management Specialist,"[-0.007595145609229803, 0.024071602150797844, ..."
4,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n1) Medical...,**Subjective:**\n\nThe patient is a 45-year-ol...,"**Subjective:**\n\nThe patient, Mrs. Emily Tho...",Pain Management Specialist,"[-0.00022266437008511275, 0.01821352168917656,..."
5,CHRONIC PAIN SYNDROME,ROLE: Family Medicine Physician\n\n1) Medical ...,**Medical Note:**\n\n**Date:** [Insert Date of...,**Medical Note:**\n\n**Date:** [Insert Date of...,Family Medicine Physician,"[-0.0019984173122793436, 0.018674982711672783,..."
6,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n1) Medical...,**Subjective:**\nThe patient is a 52-year-old ...,"**Subjective:**\nThe patient, Jane Doe, is a 5...",Pain Management Specialist,"[-0.0014946127776056528, 0.02301930822432041, ..."
7,CHRONIC PAIN SYNDROME,ROLE: Family Medicine Physician\n\n1) Medical ...,**1. Subjective:**\nThe patient is a 45-year-o...,"**1. Subjective:**\nThe patient, Jane Doe, a 4...",Family Medicine Physician,"[-0.0065644304268062115, 0.012482728809118271,..."
8,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n1) Medical...,**Subjective:**\nThe patient is a 45-year-old ...,"**Subjective:**\nThe patient, Jane Doe, is a 4...",Pain Management Specialist,"[0.0013666421873494983, 0.02832229994237423, 0..."
9,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n1) Medical...,**Subjective:**\nThe patient is a 48-year-old ...,"**Subjective:**\nThe patient, Mrs. Linda Thomp...",Pain Management Specialist,"[-0.003352179192006588, 0.019855735823512077, ..."
10,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n1) Medical...,**Subjective:**\nThe patient is a 45-year-old ...,"**Subjective:**\nThe patient, Emily Thompson, ...",Pain Management Specialist,"[-0.008799700066447258, 0.025026049464941025, ..."
11,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\nScenario:\...,**Subjective:**\nThe patient is a 45-year-old ...,"**Subjective:**\nThe patient, Jane Doe, is a 4...",Pain Management Specialist,"[-0.012626558542251587, 0.031761378049850464, ..."
12,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n1) Medical...,**Subjective:**\nThe patient is a 47-year-old ...,"**Subjective:**\nThe patient, Mr. Johnathan Gr...",Pain Management Specialist,"[-0.010753343813121319, 0.029025062918663025, ..."
13,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n1) Medical...,"**Subjective:**\nThe patient, a 45-year-old Ca...","**Subjective:**\nThe patient, Jane Doe, a 45-y...",Pain Management Specialist,"[0.01632937602698803, 0.02472507767379284, 0.0..."
14,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n1) Medical...,**Subjective:**\nThe patient is a 52-year-old ...,"**Subjective:**\nThe patient, John Doe, is a 5...",Pain Management Specialist,"[-0.014750635251402855, 0.01898282580077648, 0..."
15,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n1) Medical...,Rejected,Rejected,Rejected,"[-0.01371984463185072, 0.022161170840263367, 0..."
16,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n1) Medical...,Rejected,Rejected,Rejected,"[-0.007321719545871019, 0.02249571867287159, 0..."

In [14]:
from gen_utils import semantic_similarity_functions
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
mean_rejected_included= (df.embedding # extract 'embeddings' for each group
.apply(np.stack).reshape(-1, 1) # turns sequence of arrays into proper matrix
.apply(cosine_similarity) # the magic: compute pairwise similarity matrix
.apply(np.mean))

mean_rejected_included

AttributeError: 'Series' object has no attribute 'reshape'

In [32]:
df= pd.read_csv("/h/ahmad/SynthDataGen/Synthetic_Data_Gen/data/output/notes_onVector/CHRONIC PAIN SYNDROME_2024-05-15_with_embeding.csv", sep="|")
df.head()

,Disease Description,Scenario,Note,Polished Note,Role,embedding
0,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n1) Medical...,**Subjective:** \nThe 45-year-old female patie...,"**Subjective:** \nThe patient, Ms. Jane Doe, a...",Pain Management Specialist,"[-0.0056213503703475, 0.027141816914081573, 0...."
1,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n** Medical...,**Subjective:**\nThe patient is a 45-year-old ...,"**Subjective:**\nThe patient, Jane Doe, a 45-y...",Pain Management Specialist,"[-0.015071071684360504, 0.02452823892235756, 0..."
2,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n1) Medical...,**Subjective:**\nThe patient is a 46-year-old ...,"**Subjective:**\nThe patient, Mrs. Jane Doe, i...",Pain Management Specialist,"[0.006586750969290733, 0.025920720770955086, 0..."
3,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n1) Medical...,**Subjective:**\nThe patient is a 52-year-old ...,"**Subjective:**\nThe patient, Mrs. Linda Thomp...",Pain Management Specialist,"[-0.007615276146680117, 0.024071041494607925, ..."
4,CHRONIC PAIN SYNDROME,ROLE: Pain Management Specialist\n\n1) Medical...,**Subjective:**\n\nThe patient is a 45-year-ol...,"**Subjective:**\n\nThe patient, Mrs. Emily Tho...",Pain Management Specialist,"[-0.00022266437008511275, 0.01821352168917656,..."

In [31]:
import pandas as pd
import json
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity



# Convert JSON strings back to lists
df['embedding'] = df['embedding'].apply(json.loads)

# Ensure the column is of type float
df['embedding'] = df['embedding'].apply(lambda x: np.array(x, dtype=float))

# Stack embeddings into a 2D array
embeddings = np.vstack(df['embedding'].values)

# Compute cosine similarity
similarity_matrix = cosine_similarity(embeddings)

# Exclude self-similarities (diagonal elements)
np.fill_diagonal(similarity_matrix, np.nan)

# Calculate the average score, excluding NaN values
average_score = np.nanmean(similarity_matrix)

average_score

0.9229236558360676

In [33]:
pd.set_option('display.max_colwidth', None)

# Loop through the 'Polished Note' column and print its content
for note in df['Polished Note']:
    print(note)
    print("\n" + "-"*80 + "\n")  # Separator for better readability between notes

**Subjective:**
The patient, Ms. Jane Doe, a 45-year-old female, presents with a history of chronic lower back pain, described as persistent with a severity of 7/10, lasting more than six months. The pain occurs daily and worsens with physical activity, significantly impacting her work and household tasks. Previous management with NSAIDs provided insufficient relief. She has a familial history of fibromyalgia and a personal history of a lower back sprain. Her hypertension is controlled with medication. She reports disrupted sleep due to pain, averaging 4-5 hours per night, a diet with insufficient fresh fruits and vegetables, and a sedentary lifestyle. She is a non-smoker with moderate alcohol use on weekends and denies recreational drug use. Ms. Doe is motivated to follow medical advice to improve her condition.

**Objective:**
On examination, there is tenderness at the lumbar paraspinal muscles and reduced lumbar range of motion; however, there are no neurological deficits. The patient's vital signs are stable, and she is afebrile.

**Assessment:**
Ms. Doe is diagnosed with Chronic Pain Syndrome (CPS), considering the long duration of pain, associated life impact, and previous diagnosis of lower back sprain. The absence of neurological deficits and tenderness at the lumbar paraspinal muscles suggests a musculoskeletal component to her pain.

**Plan:**
1. Order an MRI of the lumbar spine to investigate potential structural causes for chronic low back pain.
2. Initiate physical therapy sessions twice a week for six weeks to improve mobility and strengthen the back muscles.
3. Begin cognitive-behavioral therapy (CBT) sessions once a week for three months to address the psychological impact of chronic pain and develop coping strategies.
4. Prescribe gabapentin, starting with a dose of 300 mg, oral route, once daily at bedtime, with plans to titrate up based on response and tolerability.
5. Recommend lifestyle changes to include a balanced diet rich in fruits and vegetables and to gradually increase physical activity as tolerated.
6. Encourage improved sleep hygiene and consider sleep evaluation if no improvement with pain management.
7. Schedule a follow-up appointment in four weeks to evaluate the response to the medication and therapies, and to review the results of the MRI.
8. Advise Ms. Doe to monitor her blood pressure regularly due to the initiation of gabapentin and her history of hypertension.
9. Provide educational materials on chronic pain management and resources for support groups.
10. Reassure Ms. Doe that the treatment plan will be adjusted as needed based on her response and MRI findings.

Ms. Doe has been advised of the treatment plan and has expressed understanding and willingness to comply. She has adequate insurance coverage for the proposed interventions.

--------------------------------------------------------------------------------

**Subjective:**
The patient, Jane Doe, a 45-year-old Caucasian female, presents with moderate to severe chronic pain localized to the lower back, ongoing for more than six months. She reports daily pain with variable intensity, which has been impacting her ability to perform job duties and engage in social activities. Associated symptoms include insomnia, related to pain, and anxiety, with a noted decrease in the range of motion. Despite these challenges, she is motivated to adhere to medical advice and treatment plans. She has a high level of health literacy, is a college graduate, and works full-time as an administrative assistant. Her sleep is poor, averaging 4-5 hours per night due to pain. Diet is unbalanced with sporadic meal patterns and exercise is limited due to pain. She occasionally consumes alcohol, about one drink per week, and denies tobacco or illicit drug use. Her family medical history is notable for rheumatoid arthritis in her mother and hypertension in her father. She has a history of anxiety disorder and has used ibuprofen intermittently, with no long-term medications or known drug allergies.

**Objective:**
Physical examination reveals limited lumbar range of motion and tenderness over the lumbar paraspinal muscles. The patient's vital signs are stable and within normal limits.

**Assessment:**
The patient is diagnosed with Chronic Pain Syndrome (ICD-10: G89.4). Her chronic pain is likely multifactorial, with contributions from her physical condition, psychological factors including anxiety, and lifestyle habits. The absence of specific pathology on the physical exam and history suggests a non-specific musculoskeletal origin.

**Plan:**
1. Await results of a recent lumbar spine MRI to rule out specific spinal pathologies.
2. Initiate a multimodal pain management plan:
   - Physical Therapy: Attend sessions twice a week for 6 weeks to improve mobility and strength.
   - Cognitive-Behavioral Therapy: Weekly sessions to address psychological aspects of chronic pain and to develop coping strategies.
   - Medication: Start Gabapentin (Neurontin) 300mg oral capsules, 1 capsule at bedtime for 1 week, and then increase as tolerated to 1 capsule three times a day. A quantity of 90 capsules with three refills is prescribed.
3. Follow-Up: Schedule a review of the patient's progress in one month (4 weeks) to adjust the treatment plan as necessary and to discuss the MRI results.
4. Referral: Refer the patient to Dr. Emily Thompson, a clinical psychologist specializing in chronic pain management, if psychological factors are significantly contributing to the pain syndrome.
5. Lifestyle Adjustments: Encourage the patient to aim for a more consistent sleep schedule and balanced diet. Explore pain-adapted exercise options to increase physical activity levels as tolerated.
6. Monitor for side effects of Gabapentin and effectiveness in managing pain symptoms.
7. Continue to assess and address any barriers to the patient's adherence to the treatment plan.

The patient has been informed of the treatment plan and has expressed understanding and agreement to proceed with the proposed interventions.

--------------------------------------------------------------------------------

**Subjective:**
The patient, Mrs. Jane Doe, is a 46-year-old Caucasian female presenting with a persistent moderate to severe pain impacting daily activities and lasting over six months. She reports increased discomfort during cold weather and occasional sleep disruptions due to pain. She has a previous diagnosis of fibromyalgia and a family history of autoimmune diseases. Past medication trials included NSAIDs with limited benefit. Mrs. Doe describes minimal physical activity due to pain, an average sleep of 6-7 hours with frequent disturbances, and a diet lacking in fresh vegetables and fruits. She reports no tobacco use, moderate alcohol consumption on weekends, and no illicit drug use. Mrs. Doe is a high school teacher by profession, lives in a mid-sized city with moderate pollution levels, and has moderate access to healthcare resources. She is open to non-pharmacological interventions and expresses willingness to adhere to the prescribed treatment plan.

**Objective:**
Physical examination reveals tenderness in the thoracic paraspinal muscles and a limited range of motion due to discomfort. The neurological examination is normal without focal deficits.

**Assessment:**
The patient is diagnosed with Chronic Pain Syndrome (CPS) with a background of fibromyalgia. The clinical presentation and history support the diagnosis. The differential diagnosis includes other causes of chronic pain such as structural abnormalities, which will be evaluated with an MRI, and systemic conditions, which will be assessed with bloodwork.

**Plan:**
- Physical therapy twice a week for three months to improve mobility and manage pain.
- Cognitive-behavioral therapy sessions once a week to address psychological aspects of chronic pain.
- Pharmacotherapy initiation with a low-dose tricyclic antidepressant (Amitriptyline) at 10mg orally before bedtime, with titration up as tolerated for pain management.
- Pregabalin 75mg twice daily for neuropathic pain.
- Scheduled follow-up in 4 weeks to assess medication efficacy and side effects.
- Order MRI of the Thoracic Spine to rule out structural abnormalities.
- Order CBC, CMP, TSH, Vitamin D levels, and ESR to evaluate for systemic causes of chronic pain.
- Educate the patient about the treatment plan and the importance of adherence to achieve optimal outcomes.
- Encourage Mrs. Doe to improve her diet by incorporating more fresh vegetables and fruits and to attempt light physical activities as tolerated.
- Reassess at the follow-up visit for her response to the treatment and make any necessary adjustments.

--------------------------------------------------------------------------------

**Subjective:**
The patient, Mrs. Linda Thompson, is a 52-year-old female presenting with constant, dull, aching pain in the lower back and knees, rated 7/10, which has persisted for over 3 months. She reports that the pain exacerbates with movement and affects her sleep and daily functioning. She has a previous diagnosis of fibromyalgia and hypertension, which is controlled on Lisinopril. The patient's family history is significant for osteoarthritis. She denies any known drug allergies, uses ibuprofen occasionally, and has no history of drug or tobacco use but drinks alcohol socially. Her lifestyle includes a sedentary job, poor sleep, and a diet high in processed foods with minimal exercise. She has expressed concerns about potential medication side effects and dependency.

**Objective:**
Physical examination revealed tenderness in the lower back and knee joints and a reduced range of motion in the affected areas, with no redness or swelling. The patient is normotensive with well-controlled blood pressure.

**Assessment:**
Chronic Pain Syndrome likely secondary to fibromyalgia, with contributing factors from lifestyle and work environment. No evidence of acute inflammatory or structural joint disease at this time.

**Plan:**
1. Order an MRI of the lumbar spine to investigate structural causes of the pain.
2. Initiate cognitive-behavioral therapy to address pain perception and coping strategies.
3. Prescribe Amitriptyline 25 mg orally once daily at bedtime for neuropathic pain management.
4. Start a graded exercise program to gradually improve mobility and reduce pain.
5. Refer to a physical therapist, Dr. Emily Sanders, for a tailored exercise program focusing on pain management and mobility improvement.
6. Schedule a 4-week follow-up to reassess pain level and evaluate the efficacy of Amitriptyline and other interventions.
7. Encourage lifestyle modifications including improving sleep hygiene, dietary changes to reduce processed food intake, and increasing engagement in physical activities such as swimming.
8. Educate the patient on the importance of adherence to the treatment plan and address concerns regarding medication side effects and dependency, ensuring comprehensive understanding and collaboration in the management of her condition.

--------------------------------------------------------------------------------

**Subjective:**

The patient, Mrs. Emily Thompson, is a 45-year-old Caucasian female presenting with a chief complaint of constant lower back and joint pain with a severity of 7/10, which has persisted for over six months. The pain is experienced on a daily basis, intensifies towards the end of the day, and sometimes radiates to the legs. This impacts her ability to perform daily activities, such as walking or standing for extended periods. She reports a history of fibromyalgia diagnosed two years ago, no known drug allergies, and limited success with previous NSAID treatment. Her mother had rheumatoid arthritis. Mrs. Thompson has a sedentary lifestyle with minimal exercise, poor diet, poor sleep quality, moderate alcohol consumption on weekends, no tobacco or illicit drug use, and is currently not on any medication. She expresses concerns about medication side effects but is cooperative with medical advice.

**Objective:**

On physical examination, Mrs. Thompson exhibited tender points consistent with fibromyalgia, limited lumbar spine range of motion, and pain upon palpation of the affected joints. No acute distress was noted. The patient's vital signs are within normal limits at the time of consultation.

**Assessment:**

Mrs. Thompson is diagnosed with Chronic Pain Syndrome (ICD-10: G89.4), likely exacerbated by her underlying fibromyalgia. There are no signs of acute inflammatory or structural pathology at this time, though we are awaiting further test results to complete our assessment.

**Plan:**

1. Prescribe duloxetine 30 mg orally, once daily for four weeks; may increase to 60 mg once daily depending on tolerance and effect.
2. Initiate physical therapy sessions twice a week for six weeks to improve mobility and decrease pain.
3. Refer to Dr. Sarah Johnson, a clinical psychologist, for cognitive-behavioral therapy to address the psychological aspects of chronic pain.
4. Recommend mindfulness-based stress reduction techniques to aid in pain management.
5. Instruct Mrs. Thompson to improve sleep hygiene and to consider dietary modifications aimed at reducing processed food intake.
6. Advise on the importance of gradually increasing physical activity as tolerated.
7. Schedule a follow-up visit in six weeks, or sooner if the pain worsens or if there are concerns about medication side effects.
8. Order blood work, including CBC, ESR, and CRP, to rule out other inflammatory conditions.
9. Request an MRI of the lumbar spine to evaluate for potential structural pathology.
10. Await results of the blood tests and MRI, and adjust the treatment plan as necessary based on these findings.

Mrs. Thompson has been provided with detailed explanations of all parts of the treatment plan and has been encouraged to reach out with any questions or concerns before the next appointment.

--------------------------------------------------------------------------------

**Medical Note:**

**Date:** [Insert Date of Encounter]

**Physician:** [Your Name], M.D., Family Medicine Physician

**Patient:** Jane Smith, 45-year-old female

**Subjective:**
The patient, Jane Smith, is a 45-year-old Caucasian female presenting for a follow-up visit for chronic pain management. She reports a chronic pain severity of 7/10, with daily episodes lasting more than 3 months. The pain exacerbates with movement and impacts her ability to perform routine tasks. She has a diagnosis of Fibromyalgia, confirmed two years prior, and a family history of osteoarthritis. She has trialed multiple NSAIDs with minimal relief. The patient mentions poor sleep quality, a high-fat diet, and minimal exercise due to pain. She is a non-smoker and consumes alcohol moderately on weekends. She denies any recreational drug use and expresses a desire to continue light gardening, which is presently restricted by pain. There are no known medication allergies or other chronic conditions. She is generally cooperative with medical advice but has occasional difficulties adhering to the medication regimen due to side effects.

**Objective:**
The patient has tender points on physical examination, consistent with Fibromyalgia; there are no signs of inflammation or injury. Vital signs are within normal limits. The patient is currently on medical leave from her job as an administrative assistant and lives in an urban setting with adequate access to healthcare facilities and amenities.

**Assessment:**
A 45-year-old female with Chronic Pain Syndrome, likely secondary to Fibromyalgia. Differential diagnosis includes other causes of chronic pain, which the MRI will help to elucidate or rule out. No new acute findings are noted at this time.

**Plan:**
1. Await results of the MRI of the lumbar spine for further assessment.
2. Continue Gabapentin 300mg, capsules, orally, three times a day for 30 days, with a quantity of 90 capsules.
3. Physical therapy is prescribed twice a week for 6 weeks, focusing on pain management and mobility.
4. Cognitive-behavioral therapy with a licensed psychologist, weekly sessions for 2 months, focusing on pain management.
5. Referral to pain specialist Dr. Jane Doe for evaluation regarding a comprehensive pain management program. The referral is due to the need for specialized care in chronic pain management.
6. Counsel patient on the importance of a balanced diet and pain-appropriate physical activity.
7. Review and manage side effects of medication, ensuring optimal adherence.
8. Schedule follow-up appointment to review MRI results and adjust the treatment plan as necessary.
9. Encourage maintenance of good sleep hygiene to potentially alleviate some pain symptoms.

**Next Appointment:** Scheduled in 4 weeks for follow-up, or sooner if MRI results warrant an earlier discussion.

**Signature:** [Your Name], M.D.

[Insert Clinic Address and Contact Information]

--------------------------------------------------------------------------------

**Subjective:**
The patient, Jane Doe, is a 52-year-old Caucasian female presenting with moderate to severe chronic pain, persisting for more than 6 months. She reports limited mobility and intermittent tingling in her extremities. The pain occurs daily with variable intensity and significantly impacts her ability to perform basic household tasks, leading to a decreased quality of life. Sleep quality is poor, often disrupted by pain. The patient has a history of intervertebral disc degeneration and has tried NSAIDs in the past with limited relief. She has no known drug allergies and is hypertensive. The patient leads a sedentary lifestyle, largely due to pain, with a diet consisting mostly of processed foods. She does not smoke, consumes alcohol socially, and denies any illicit drug use. Previously enjoyed activities such as hiking are now limited to light walks. She is currently on medical leave from her healthcare-related job due to her symptoms. The patient has a high level of health literacy and has demonstrated good compliance with medical advice in the past.

**Objective:**
The physical examination reveals diffuse muscle tenderness but no specific nerve root signs on the neurological exam. Musculoskeletal exam shows reduced range of motion in the lumbar spine. Blood work to measure ESR and CRP levels is pending.

**Assessment:**
The patient is diagnosed with Chronic Pain Syndrome (ICD-10: G89.4), possibly exacerbated by or related to her history of intervertebral disc degeneration. No definitive structural cause has been identified yet, pending MRI results. The patient's symptoms are consistent with her diagnosis and are significantly impairing her quality of life and functional status.

**Plan:**
1. Prescribe Gabapentin treatment at a dose of 300 mg capsules, taken orally, three times daily for two weeks, with a total quantity of 42 capsules. This is to manage neuropathic aspects of the chronic pain syndrome.
2. Schedule a re-evaluation in two weeks to assess the efficacy of Gabapentin and monitor for potential side effects.
3. Refer the patient to physical therapy for pain management techniques, which may help improve mobility and reduce pain.
4. Schedule an MRI of the lumbar spine to rule out structural causes for chronic pain. The MRI is to be completed as soon as possible.
5. Review ESR and CRP test results upon receipt to evaluate for underlying inflammatory processes.
6. Encourage the patient to gradually incorporate a balanced diet with more fresh produce and to engage in gentle exercises as tolerated, which may complement the pain management plan.
7. Consider referral to a dietician for nutritional counseling to support lifestyle changes that may benefit her condition.

--------------------------------------------------------------------------------

**1. Subjective:**